var candidates = [{
    "first_name": "Pete",
    "last_name": "Buttigieg",
    "bio": "Pete is the Mayor of South Bend, Indiana. He is one of Americas youngest mayors, and the Washington Post has called him 'the most interesting mayor you have never heard of.' An officer in U.S. Navy Reserve, Pete took a leave of absence to serve in Afghanistan in 2014.\n",
    "vision": "The DNC needs new leadership to deliver a fresh start. The solutions we need to rebuild our Party will come from our local communities, our states and territories- not from Washington. The next Democratic chair must speak to the common threads that bring together our diverse constituencies, not be afraid to reach out to new ones, and build a new future for the Party around our shared values. \n",
    "platform": "The Democratic Party needs a fresh start. However much pride we take in the work that has brought us to this point, we must confront the fact that our presence in state legislatures, statewide offices, and Congress is at its lowest point in nearly a century. Even if we had won the White House last year, our party would be facing serious challenges today. But for all of our challenges, there are solutions. We will develop our bench by focusing on the long-term needs of our party.\n\nWe will harness new and existing sources of financial support, and use it to invest in real infrastructure for our local and state parties so we can more effectively organize at every level, engage every part of our membership, and think beyond one election cycle at a time. It is time to invest in real on-the-ground organizing and make it the heart of our national work as a party. We will run the Democratic National Committee as a resource for state and local parties and nationally organized allies like our friends in organized labor, to meet their needs and support their work. A stronger partnership with our communities and constituencies is the only way to ensure we turn out our voters, and attract new support.\n\nThis will require resources, but that is only the beginning. Finding our way forward means leading with our values, returning to the basics of running campaigns and winning elections, acting from the ground up, modeling democratic practices, and innovating for the future.",
    "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/PeteButtigieg.JPG/443px-PeteButtigieg.JPG",
    "website": "www.petefordnc.com ",
    "twitter": "@PeteforDNC",
    "facebook": "https://wwww.facebook.com/PeteforDNC/?fref=ts"
}, {
    "first_name": "Jaime",
    "last_name": "Harrison",
    "bio": "Jaime Harrison is the Chair of the South Carolina Democratic Party. He previously worked for Congressman James E. Clyburn, the Podesta Group, the non-profit College Summit, and his high school alma mater. Born to a teen mom in rural South Carolina, Jaime was the first in his family to go to college.",
    "vision": "Jaime can unite the Democratic Party because he has done it-as Floor Director for House Majority Whip James E. Clyburn, he was responsible for securing 218 votes in a very diverse Caucus.\nJaime will transform our Party into a community organization working in our neighborhoods addressing day-to-day issues faced by middle and working class voters.\nJaime knows what its like to run a State Party organization in a red state. As DNC Chair, he will help all State Parties galvanize the grassroots to resist Trump's harmful policies and draw stark distinctions so that all voters know that Democrats have an agenda that will improve their lives.",
    "platform": "To rebuild the Democratic Party Jaime will:\n\u2022Invest in all 50 State Parties (plus those in the territories and Democrats Abroad) by increasing the State Partnership Program to $12,000 a month and easing restrictions on how that money is spent.\n\u2022Provide State Parties with professional and specialized operations, capabilities, and in-kind services on a permanent basis through regional Caucus hubs, i.e., provide political, press, fundraising, and tech staff dedicated to serve state parties in each region\n\u2022Empower regional Caucuses through joint fundraising and candidate support efforts and ensure Caucuses have dedicated funds to support local candidates and efforts\n\u2022Work with the FEC and Congress to make sure that super PACs and other political organizations are held to the same standard as State Parties\n\u2022Build a deep bench of potential Democratic candidates who are connected to their communities on every level by supporting state and national political training fellowships modeled after South Carolinas James E. Clyburn Political Fellowship\n\u2022Give young people a seat at the decision table by creating a Vice Chair position for those 35 and younger\n\u2022Spark a new wave of political technological innovation by creating a tech competition to address party eld and message outreach efforts\n\u2022Promote and invest in community-based activities and messaging modeled after SC Democrats Care\n\u2022Establish a surrogate program to assist states and local parties with securing Democratic speakers\n\u2022Host strategy and message coordination sessions with affiliated groups from the DCCC and DSCC and DGA to DLCC and DMO\n\u2022Provide financial and legal assistance to State and Local Parties and legislators to stop gerrymandering and challenge gerrymandered districts in court\n\u2022Fight to end GOP voter suppression and make voting more convenient\n\u2022Push to get big money out of politics and cultivate small-dollar donors at the national, state, and local levels\n\u2022Support Democratic candidates up and down the ticket",
    "photo": "http://imgur.com/a/6mp4D",
    "website": "www.jaimefordncchair.com",
    "twitter": "@Harrison4DNC",
    "facebook": "https://www.facebook.com/JaimeForDNC/"
}, {
    "first_name": "Tom",
    "last_name": "Perez",
    "bio": "\nThe son of immigrants, Tom grew up in Buffalo where he learned the values of a union town: hard work, integrity, service, & perseverance. Tom has spent his career fighting and organizing opportunity from good jobs and higher wages to access to the ballot, safe places to worship, and more.",
    "vision": "In the years ahead, we must strengthen our team, and our bench, from the ground up. And we must stand up to protect President Obamas accomplishments.\nBut most of all, we need to listen. We need to listen to Democrats at every level, empowering them to fight for progressive values and a vision of opportunity and optimism. And we need to listen to voters, up and down the ballot, who are asking us to stand behind them. Together, we will build the party every Democrat and every American deserves.",
    "platform": "FIGHTING FOR OUR VALUES. Standing up for what we believe is a critical part of who we are as progressives and as Democrats. To fight for our values and protect our rights, we will:\n\u2022Fight voter suppression and disenfranchisement by working with state parties and progressive groups to stop unjust laws\n\u2022Target gerrymandering where it starts by working to elect more Democratic state legislatures and governors\n\u2022Support state parties to find, recruit and train candidates for office at every level of the ballot, from school board to senate, who reflect our big tent and diverse party\n\u2022Build a robust Voter Empowerment Office with a fully-staffed team operating year round that would:\n\u2022Support states by creating a regional structure with 1 person dedicated to working with EVERY state to proactively monitor and fight voting issues, from helping build relationships with election administrators to fighting unjust voter ID laws and gerrymandering.\n\u2022Make facts on Trump and the Republicans easily accessible on the DNCs website to help Democrats all over the country stay engaged and ready to fight\n\u2022ADVOCATING IN EVERY ZIP CODE. No matter where they live every American should hear our message of inclusion and opportunity. To make sure every zip code counts, we will:\n\u2022Build a deep bench of Democrats ready to run who reflect our big tent and diverse party, including providing national and regional candidate training and recruitment\n\u2022Ensure those trainings prepare women, LGBTQ and under-represented groups for their runs for office\n\u2022ORGANIZE FOR OPPORTUNITY. The DNC will build an increased grassroots effort to speak directly with voters in every community, from rural to urban, by:\n\u2022Recruiting experienced organizers and building a permanent organizing department\n\u2022Develop a program to train the next generation of diverse advocates and leaders to make sure our outreach reflects our party, including women, LGBTQ, African Americans, Asian Americans and Pacific Islanders, Latinos, and rural Americans\n\u2022Invest in local organizers and parties by increasing training and support for neighbor-to-neighbor outreach\n\u2022Building a strategy that supports all 50 states, the District of Columbia, territories and Democrats Abroad to ensure we reach Democrats regardless of where they are\n\u2022Listening to state parties to learn from them the best ways to organize\n\u2022Increase our new voter registration efforts to every single year, not just presidential one.",
    "photo": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Official_portrait_of_United_States_Secretary_of_Labor_Tom_Perez.jpg/420px-Official_portrait_of_United_States_Secretary_of_Labor_Tom_Perez.jpg",
    "website": "tomperez.org",
    "twitter": "@TomPerez",
    "facebook": "https://www.facebook.com/TomPerez/"
}, {
    "first_name": "Ray",
    "last_name": "Buckley",
    "bio": "Ray Buckley is Chair of the New Hampshire Democratic Party. He has overseen the most dramatic record of Democratic victories in his states history, including bucking national tides in 2014 and 2016. Buckley is the first openly gay Vice-Chair of the Democratic National Committee.",
    "vision": "Experience in State & Local Party Building:\nUnder Rays leadership, Democrats have consistently won elections in a purple state-in no small part due to a strong, grassroots-driven state party.\n\nA Perspective from Outside the Beltway:\nRay understands elections are won by volunteers in communities across the country-not by consultants in Washington. The DNC needs to focus on winning thousands of state & local races not just the White House.\n\nA Commitment to Our Grassroots:\n\nRays bold plan to reinvigorate our state parties reflects his commitment to our grassroots. As Chair, he will be devoted to leading, reforming, & growing the Democratic Party.",
    "platform": "Part 1: A Plan to Strengthen our State Parties\n\nElections are won in towns & cities across the country-not in Washington, DC. Vibrant state parties are critical to winning offices from the municipal level all the way to the White House.\nRays 15-point plan for the DNC strengthens our state parties by:\n\u2022Providing a guaranteed base of $10,000 per month to each of the 57 state & territory parties.\n\u2022Granting up to $15,000 per month for critical state-specific projects or programs.\n\u2022Hosting an intensive, yearly training program for up to four staff members per state, at no cost to state parties.\n\u2022Establishing an incentive program to reduce Executive Director turnover.\n\u2022Providing long-term staff of the Democratic Party with healthcare & retirement security.\n\u2022Opening a satellite office in Silicon Valley & developing innovative technological tools for use by all Democratic campaigns.\n\u2022Using the newly-authorized building fund to open offices in every congressional district, allowing for year-round political organizing.\n\u2022Prohibiting the DNC from signing Joint Fundraising Agreements with any candidate in a contested primary.\n\u2022Ensuring every state receives a top surrogate for a fundraising event each year.\n\u2022Continuing our relationship with the National Voter File Cooperative.\n\u2022Using DNC funds for constituency engagement, field programs, voter protection, & get-out-the-vote activities instead of TV ads.\n\u2022Expanding the ASDC to include on-the-road staff who will provide in-state trainings for local parties.\n\u2022Increasing staff to strengthen voter registration & protection efforts.\n\u2022Creating a permanent desk within every constituency caucus.\n\u2022Requiring DNC staff to work at least ten days per year out of a state party office.\u2022\nPart 2: A Plan for Reform\nBefore we address our ground game or message, we must first clean our own house & take a fresh look at our national convention & nominating process.\nMy plan ensures governance of the DNC is more transparent & accountable by:\n\u2022Removing decisions about the presidential nominating process for the Chairs sole prerogative.\n\u2022Reforming the role of superdelegates to ensure votes reflect that of their states electorates.\n\u2022Providing DNC members with financial & political reports to ensure greater transparency.\n\u2022Empowering DNC officers to overturn decisions of the DNC Chair & approve DNC contracts.\n\u2022Ensuring the DNCs leadership & hiring reflects the full diversity of the Democratic Party.",
    "photo": "https://upload.wikimedia.org/wikipedia/commons/e/e9/Ray_Buckley.png",
    "website": "rayfordnc.com",
    "twitter": "@ChairmanBuckley",
    "facebook": "www.facebook.com/rayfordnc"
}, {
    "first_name": "Keith",
    "last_name": "Ellison",
    "bio": "Keith moved to Minneapolis from Detroit to attend law school in 1990. In 2006, he was the first Muslim elected to Congress and has boosted his district turnout from lowest in MN to the highest. He served on the DNC Platform Drafting Committee and is co-chair of the Congressional Progressive Caucus.",
    "vision": "Democrats win when we empower the grassroots and fight for the issues that improve peoples lives. We must energize Democratic activists across the country and give them the tools to build the Party from the bottom up. Beyond a 50-state strategy, we need a 3,143-county strategy.\nWe must reclaim our history as the Party that stands with working people. That means fighting attempts by the Trump White House and Republican-controlled states to roll back affordable health care, worker wages and protections, civil rights, and a womans right to choose at every turn.",
    "platform": "1. PUTTING VOTERS FIRST\n\u2022 Engage with allies in party rebuilding, including message development, outreach, and grassroots mobilization.\n\u2022 Study and disseminate best practices for organizing to candidates on all levels. Resurrect national training programs.\n\u2022 Encourage candidates to set goals to boost turnout by 3-7% over the last comparable election, with separate goals for new and infrequent voters. Collaborate with national, state and local partners to boost registration.\n\u2022 Protect against voter suppression and promote laws that encourage voter participation.\n2.BEYOND THE BELTWAY\n\u2022 Increase State Partnership Project funding to $10,000 / month, with additional funding available for state and local parties to apply for to build programs.\n\u2022 Convene stakeholders to develop a strategy to win back state legislatures and governors for 2020 redistricting.\n\u2022 Host candidate training programs to win local races, creating diverse qualified candidates ready to run for higher office.\n\u2022 Locate DNC staff across the country.\n3.FOCUS ON WORKING PEOPLE\n\u2022Strengthen relationships with Labor.Commit to using 100 % union hotels, venues and vendors.\n\u2022 Set a goal that low - dollar contributions account for 33 % of revenue.\n  4.ACCOUNTABILITY & INCLUSION\n\u2022Ensure all have a voice in how their Party operates, including regional calls with county parties and local organizations.\n\u2022Regular briefings from the Chair and Department Directors to the DNC Executive Committee and state party chairs.\n\u2022Ensure Young Dems groups have DNC financial support and a voice in decision making.\n\u2022Intentional hiring process that creates a diverse applicant pool and candidate selection.\n\u2022 Designate outreach and organizing staff lead for each of the constituency communities in the charter and bylaws.\n\u2022 Where possible, hire internally to build infrastructure.\n\u2022 Set aggressive goals for external vendor contracts from Rising American Electorate.\n\u2022 Begin development of the 2020 presidential primary debate schedule as early as practicable, and seek DNC Executive Committee endorsement of it.Convene weekly working group of presidential campaign reps during the primary season for briefings on DNC activity.Support a successful process from the Unity Reform Commission to institute superdelegate reform.\n5.TECHNOLOGY\n\u2022 Convene a working group to assess polling and analytics from this cycle.\n\u2022 Create a permanent cybersecurity advisory group.\n\u2022 Ensure state party access to HFA data and future presidential campaign data.\n\u2022Open an Innovation Hub in Silicon Valley to tap the talents of our top innovators.\n\u2022Work with state parties to enhance the tools and data on the voter file and work closely with state parties and the National Voter File Cooperative.",
    "photo ": "http: //imgur.com/a/9sTEK",
    "website": "https://keithfordnc.org/",
    "twitter": "@EllisonCampaign",
    "facebook": "https://www.facebook.com/KEforDNC/"
}, {
    "first_name": "Robert Vinson",
    "last_name": "Brannum",
    "bio": "Robert is a retired vet & DC activist, Chair Emeritus, Ward5 Dems; Chair, NAACP-DC Veterans Committee; Incorporator, National Coalition on Black Civic Participation; fmr chair, DC Commission on National & Community Service; fmr president, DC Federation of Civic Assns; & fmr Ward 5 ANC Commissioner.\n",
    "vision": "I feel the DNC needs a full-time leader to work more closely with loyal grassroots Democrats, DNC State Committees, and Democrats Abroad to close the distance between message and perception of the Party. The DNC Chair must be able to advocate the vision, mission and goals of the DNC. I make a commitment to fight for all Americans so they can feel assured the principles of the Democratic Party reflect their shared values. The DNC Chair must be able to reinvigorate the Partys operations so the American public can trust, believe and have faith in the Democratic Party and its leaders. I want to join other Democrats to move the Party forward.\n",
    "platform": "The American people must know the Democratic Party is open to new ideas and all Democrats can contribute to rebuilding the Partys future. \nThe DNC Chair must be willing to listen to bring all Democrats to the table to help improve the quality of life for all Americans. Contrary to the dark vision of President Trump and the GOP; Democrats and the Democratic Party want to protect the rights and improve the quality of life for all Americans. \nDemocrats care about issues such as jobs, homeland security, economic justice, human dignity, safe environment, equal rights, young people, veterans, affordable housing, quality public education and health care. I will be a full-time fighter pushing back against the hurtful policies of President Trump and the retro and unequal GOP agenda. \nI will speak boldly, loudly and convincingly. Democrats cannot become political spectators sitting on the dock of the bay waiting for President Trumps regressive initiatives and Republican Party ideas to fail. The Democratic Party must extend a welcoming spirit to all Democrats with energy to build a strong future for the Party and for America. Grassroots Democratic coal miners in West Virginia, grassroots union members in Michigan, Ohio, and Pennsylvania, along with millennials and grassroots District of Columbia Democrats supporting seeking DC Statehood must reach out each other to rebuild the whole Democratic Party. \nI commit to real and true efforts toward Democratic Party unity. The Democratic State Committees and Democrats Abroad must have a greater role in setting the party on the correct path. Moving forward, the DNC needs a strong-willed advocate as a leader to stand in the gap and take on President Trump and GOP anti-worker, anti-minority, anti-women, anti-environment, anti-income income equality, anti-income equality, anti-science agenda. \nUnder the leadership of President Obama, the American economy grew, health care coverage expanded for more Americans, and throughout the world Americas foreign policy leadership was strengthened. The DNC must be vigilant, challenging and calling out President Trump and GOP dog whistles of racism and bigotry to misrepresent religious freedom and social tolerance. \nNow is the time for the DNC to become a force to push back attempts to turn Americans against each other. America cannot be great if its leaders do not care about bringing Democrats and righteous Americans together with a shared purpose and a hopeful vision for the future.",
    "photo": "http://imgur.com/a/5XI79",
    "website": "",
    "twitter": "@robert158",
    "facebook": ""
}, {
    "first_name": "Sally Boynton",
    "last_name": "Brown",
    "bio": "Sally Boynton Brown grew up in a working class Idaho family. A proud mother, wife, community leader, small business owner, and mentor; as Idaho's executive director Sally quickly assumed a national leadership role as President of the Association of State Democratic Party Executive Directors (ASDED).",
    "vision": "We are at a crossroads. We can choose to move ourselves past our defeats by looking honestly at the root causes or we can perish as a party. We need to give ourselves permission to take risks and embrace bold solutions.\nThe most important role for the DNC is to engage and empower every citizen. We must involve everyone, and remember that voting is just the first step to creating a vibrant democracy. Together we can revolutionize the Party for generations to come!\nIt is as simple as this we must conquer our fears and change our party before we can create the change we want to see in our nation and our world.\nBe bold, take risks and join me!",
    "platform": "Building a 21st century organization will require that we move from our old ways of operating to create a new way of conducting ourselves, complete with new and innovative supporting structure and procedures. To fully understand the massive systemic changes I am proposing, we should start with some terms that may be new to many.\n\nOld-Power~ Centralized and top down. Relies on consolidation of power, rigid hierarchy, and leveraging anything with value (knowledge, relationships, trust etc) as currency to be exchanged for power. The shape of an 'old-power' structure is a pyramid tapering up to a few people who utilize the masses to maximize their own power.\n\nNew-Power~ Decentralized and relies on sharing and empowering each other. Relies on collaboration, transparency, and participation. By bringing diverse thinkers together we can access the best collaborative solutions. The shape of a 'new-power' structure is a circle where everyone leads the way and is equal. Though some hierarchy may be found in large organizational structures, elected leaders are in service to the people and aim to maximize the shared power of the organization; they do not claim that power for personal agendas. The highest goal is to promote democratic processes and amplify the voices of our members.\n\nCouncils and Workgroups~ We will form a number of new committees, I refer to as Councils and Workgroups. These groups are designed to move to a new-power system where more people are helping to make the decisions of the Party. They will each be given a focus area, a clear timeline and goals, and provided with support staff and resources. All members of the public will be encouraged to apply for these special committees which will utilize the latest technology to give access to the largest most diverse group of people.\n\nWe must shift from an Old-Power to a New-Power model of operating, and rebuild the four key pillars of our organization - Purpose, Partnership, Structure and Culture - Please read my full Blueprint for the Future for more details, and then reach out to me with your feedback!\n\nHow we go about the bold, visionary work of rebuilding our Party is up to YOU! We cannot afford to lose one single voice in this process. We must engage everyone in brainstorming and decision making to ensure the energy and passion we put into this process results in the most innovative, vibrant, resilient Democratic Party America has seen. My plan outlines a bold vision for the future of our Party.",
    "photo": "http://imgur.com/a/EvOAS",
    "website": "WeTheDNC.org",
    "twitter": "@SallyBSquared",
    "facebook": "https://www.facebook.com/wethednc/"
}, {
    "first_name": "Samuel",
    "last_name": "Ronan",
    "bio": "Samuel Ronan is a Naturalized Citizen, who came to America from Germany when he was 4. He enlisted in the US Air Force at 19, and spent five years in active duty. However, after the Government Shutdown in 2013, he chose to dedicate his life to fixing the problems America faced through politics.",
    "vision": "My vision for the Democratic Party is simple: people, country, party in that order, always! The reason being, if we take care of the men and women on the ground floor who are out there knocking on doors, making calls, soliciting donations, organizing fundraisers, press conferences, interviews, and getting our people elected at all levels of government, then everything else falls into place.\nThe other reason for a people first approach is to improve the integrity and image of the party. It is the most effective and logical means of running an organization! Furthermore, we need to be more inclusive and transparent as a Party!",
    "platform": "I believe as a Party we need to get rid of Super delegates from our Primary Process, open the voting and selection process for executive members of the DNC to the Registered Democratic voters, make our home page easier to navigate, and add a directory for DNC members, broken down by state, and further by county so that anyone can find whoever they need within the organization!\n\nOur processes for getting elected need to be made public, easily accessible, and easy to find and understand. We cannot call ourselves the Party of the People if you have to be an insider, or already a part of the highest echelons of power within the party to figure out how to move into other positions! In line with that, we must hold our elected officials accountable for their actions, or in actions during their tenure in office. If they aren't adamantly supporting the American people and our ideals as Democrats, Progressives and Liberals, 100% of the time then they don't need to be in the party, period!\n\nFinally, everyone is talking about how to engage with Millennials, and encourage grassroots programs, yet, I am the only candidate who is truly grassroots and a Millennial. I know what it takes to run for office, and how difficult it is to be an outsider with only yourself and your own resources to rely on. We have to consolidate our resources at the local levels, and enable people to run for office who don't have the same connections and resources as traditional candidates. Not only will that encourage more people to participate, but it will also allow to succeed!\n\nWe have to centralize our communications, and our funding so that the Local Parties receive the lion's share of it. We should take it a step further and have 1 Campaign manager, manage all local races or up to 10 (for larger cities), a central finance officer, and a central Communications Director who can collaborate with all candidates at once and get them the air time they need to reach out to the public! This would help prevent the over use of man power and funding trying to have 7 different campaign managers, 7 different finance officers, and 7 different Comm Directors! It would allow 18 additional people to be involved in getting 7 people elected! That is how we fight back and win!",
    "photo": "http://imgur.com/a/GEKQy",
    "website": "www.thejoesinitiative.org",
    "twitter": "@RonanForDNC",
    "facebook": "www.facebook.com/RonanForDNC"
}, {
    "first_name": "Jehmu",
    "last_name": "Greene",
    "bio": "Baptized in Democratic Party politics in Texas, Jehmu is a seasoned organizer & former Fox News analyst.She served as Womens Outreach Director & Southern Political Director at the DNC, is a former President of Rock the Vote and the Womens Media Center & a Co-Founder of DefineAmerican & VoteRunLead",
    "vision": "The DNC is mired in an old school system. We have a unique opportunity to innovate how we organize, communicate, & connect.To embrace experimentation & disruption, and respond to a chorus of disenfranchised Americans who have given up on politics & an even larger chorus looking for a home to #Resist.\nWe need an organizer as the next DNC Chair, not another politician.Transformation requires willingness, radical candor & strong change management. I am embracing the joy of rebuilding our Party w/ ideas that inspire & will deliver real results. Under my leadership, the DNC will think bigger, act bolder, & hold ourselves accountable to this moment.",
    "platform": "REIMAGINE & RESTRUCTURE PROCESSES: Retire outdated superdelegate concept\nTRANSFORM TRANSPARENCY & ACCESS: Info on how to become a Party leader to be fully disclosed, easily understood, & accessible to all\nEVERYDAY/EVERYONE/EVERYWHERE STRATEGY: Connect with Americans of every hue, gender, generation, zip code & background. Allocate $10K per month to each state w/requirement that it publish staff & contracting diversity data & conduct yearly implicit & explicit bias trainings. Invest $5 million annually in states where base is expanding, including AZ, GA & TX\nFUNDRAISING: Transform donor participation, so majority of funds come from grassroots. Allow donors to invest in specific projects\nPROJECT 50/50: 50% of staff & consultants will be based outside of DC. Set goal of at least 50% of staff & consultants to be women & 50% to be people of color/minority owned businesses\nProvide general operating grants of $25-100K to local & state parties for training, technology, staff, rural engagement, electoral efforts & candidate recruitment. Requirements: publish staff & consulting diversity data & conduct yearly implicit & explicit bias trainings\nINNOVATION HUBS Invest $100K in each state dedicated to incubate ideas & talent that embrace experimentation & disruption\nBUDGET REFORM: Millennial engagement budget: $40M in 2017, $100M in 2020. Fund 3 positions for College Dems & Young Dems: Exec Director, Comms Director, & Organizing Director. Allocate at least $1M each annually to College Dems & Young Dems operating budgets.\niDEM AWARDS: Honor innovation, best practices, community engagement, communications w/$5,000 financial awards & national & local media visibility\nMEDIA TRAINING ACADEMY: Train army of messengers to go toe-to-toe w/conservatives who lie for a living & empower them to win w/the truth\nKEEPING UP W/THE DEMOCRATS CHALLENGE: Series of film, music, & spoken word competitions that challenges creative leaders to communicate what the platform means to them & their community\nDEMOCRATS.ORG: Incorporate a community engagement platform\nTHERESISTANCE WAR ROOM: Convene rapid response calls w/ state & local leaders to connect them to daily actions\nSHIFT BATTLEFIELD FROM VOTER SUPPRESSION TO VOTER EXPANSION: Collaborate w/allies to advance new state & federal legislation that champions universal voter registration & online voting.\nVOTE 2020, A TURNOUT MOONSHOT: Devote massive resources & energy to achieving a moonshot goal of 80% turnout by 2020",
    "photo": "http://www.feminist.com/activism/jehmu.jpg",
    "website": "https://www.jehmufordnc.org/",
    "twitter": "@jehmufordnc",
    "facebook": "https://www.facebook.com/jehmufordnc"
}]
module.exports = candidates;
