var electors = [{ "Name": "Nancy L Worley", "State": "AL", "Email": "aldemocrats@gmail.com", "Phone": "334-262-2221" },
    { "Name": "Clinton M Daughtrey", "State": "AL", "Email": "aldemocrats@gmail.com", "Phone": "334-262-2221" },
    { "Name": "Greg Graves", "State": "AL", "Email": "aldemocrats@gmail.com", "Phone": "334-262-2221" },
    { "Name": "Randy B Kelley", "State": "AL", "Email": "aldemocrats@gmail.com", "Phone": "334-262-2221" },
    { "Name": "Janet May", "State": "AL", "Email": "aldemocrats@gmail.com", "Phone": "334-262-2221" },
    { "Name": "Casey Steinau", "State": "AK", "Email": "info@alaskademocrats.org", "Phone": "907-258-3050" },
    { "Name": "Lawrence A Murakami", "State": "AK", "Email": "info@alaskademocrats.org", "Phone": "907-258-3050" },
    { "Name": "Sheila A Selkregg", "State": "AK", "Email": "info@alaskademocrats.org", "Phone": "907-258-3050" },
    { "Name": "Edward Wesley", "State": "AK", "Email": "info@alaskademocrats.org", "Phone": "907-258-3050" },
    { "Name": "Alexis C Tameron", "State": "AZ", "Email": "info@azdem.org", "Phone": "602-298-4200" },
    { "Name": "Douglas Ballard", "State": "AZ", "Email": "info@azdem.org", "Phone": "602-298-4200" },
    { "Name": "Luis Heredia", "State": "AZ", "Email": "info@azdem.org", "Phone": "602-298-4200" },
    { "Name": "William G Roe", "State": "AZ", "Email": "info@azdem.org", "Phone": "602-298-4200" },
    { "Name": "Carolyn Warner", "State": "AZ", "Email": "info@azdem.org", "Phone": "602-298-4200" },
    { "Name": "Vincent Insalaco", "State": "AR", "Email": "info@arkdems.org", "Phone": "501-374-2361" },
    { "Name": "Joyce Elliott", "State": "AR", "Email": "info@arkdems.org", "Phone": "501-374-2361" },
    { "Name": "Dustin McDaniel", "State": "AR", "Email": "info@arkdems.org", "Phone": "501-374-2361" },
    { "Name": "Kasey Summerville", "State": "AR", "Email": "info@arkdems.org", "Phone": "501-374-2361" },
    { "Name": "John Burton", "State": "CA", "Email": "info@cadem.org", "Phone": "916-442-5707" },
    { "Name": "Steven K Alari", "State": "CA", "Email": "info@cadem.org", "Phone": "916-442-5707" },
    { "Name": "Becca Doten", "State": "CA", "Email": "info@cadem.org", "Phone": "916-442-5707" },
    { "Name": "Jesse Durfee", "State": "CA", "Email": "info@cadem.org", "Phone": "916-442-5707" },
    { "Name": "Mary Ellen Early", "State": "CA", "Email": "info@cadem.org", "Phone": "916-442-5707" },
    { "Name": "Alexandra Gallardo Rooker", "State": "CA", "Email": "info@cadem.org", "Phone": "916-442-5707" },
    { "Name": "Alice A Huffman", "State": "CA", "Email": "info@cadem.org", "Phone": "916-442-5707" },
    { "Name": "Aleita J Huguenin", "State": "CA", "Email": "info@cadem.org", "Phone": "916-442-5707" },
    { "Name": "Michael Kapp", "State": "CA", "Email": "info@cadem.org", "Phone": "916-442-5707" },
    { "Name": "Andrew Lachman", "State": "CA", "Email": "info@cadem.org", "Phone": "916-442-5707" },
    { "Name": "Barbara Lee", "State": "CA", "Email": "info@cadem.org", "Phone": "916-442-5707" },
    { "Name": "Otto O Lee", "State": "CA", "Email": "info@cadem.org", "Phone": "916-442-5707" },
    { "Name": "Sandra M Lowe", "State": "CA", "Email": "info@cadem.org", "Phone": "916-442-5707" },
    { "Name": "Bob Mulholland", "State": "CA", "Email": "info@cadem.org", "Phone": "916-442-5707" },
    { "Name": "Christie Pelosi", "State": "CA", "Email": "info@cadem.org", "Phone": "916-442-5707" },
    { "Name": "John A Perez", "State": "CA", "Email": "info@cadem.org", "Phone": "916-442-5707" },
    { "Name": "Melahat Rafiei", "State": "CA", "Email": "info@cadem.org", "Phone": "916-442-5707" },
    { "Name": "Susie A Shannon", "State": "CA", "Email": "info@cadem.org", "Phone": "916-442-5707" },
    { "Name": "Garry S Shay", "State": "CA", "Email": "info@cadem.org", "Phone": "916-442-5707" },
    { "Name": "Keith Umemoto", "State": "CA", "Email": "info@cadem.org", "Phone": "916-442-5707" },
    { "Name": "Maxine Waters", "State": "CA", "Email": "info@cadem.org", "Phone": "916-442-5707" },
    { "Name": "Laurence S Zakson", "State": "CA", "Email": "info@cadem.org", "Phone": "916-442-5707" },
    { "Name": "Rick A Palacio", "State": "CO", "Email": "info@coloradodems.org", "Phone": "303-623-4762" },
    { "Name": "Michael F Hamrick", "State": "CO", "Email": "info@coloradodems.org", "Phone": "303-623-4762" },
    { "Name": "Beverly Benavidez Ryken", "State": "CO", "Email": "info@coloradodems.org", "Phone": "303-623-4762" },
    { "Name": "Jeri D Shepherd", "State": "CO", "Email": "info@coloradodems.org", "Phone": "303-623-4762" },
    { "Name": "Terry L Tucker", "State": "CO", "Email": "info@coloradodems.org", "Phone": "303-623-4762" },
    { "Name": "Dominic F Balletto Jr", "State": "CT", "Email": "info@ctdems.org", "Phone": "860-560-1775" },
    { "Name": "Nancy DiNardo", "State": "CT", "Email": "info@ctdems.org", "Phone": "860-560-1775" },
    { "Name": "John W Olsen", "State": "CT", "Email": "info@ctdems.org", "Phone": "860-560-1775" },
    { "Name": "John D Daniello", "State": "DE", "Email": "delaware@deldems.org", "Phone": "302-328-9036" },
    { "Name": "Robert Gilligan", "State": "DE", "Email": "delaware@deldems.org", "Phone": "302-328-9036" },
    { "Name": "Lisa B Goodman", "State": "DE", "Email": "delaware@deldems.org", "Phone": "302-328-9036" },
    { "Name": "Karen Lynne Kirkpatrick-Valentine", "State": "DE", "Email": "delaware@deldems.org", "Phone": "302-328-9036" },
    { "Name": "Katie Solon", "State": "DA", "Email": "info@democratsabroad.org", "Phone": "202-621-2085" },
    { "Name": "Connie Borde", "State": "DA", "Email": "info@democratsabroad.org", "Phone": "202-621-2085" },
    { "Name": "John A Eastwood", "State": "DA", "Email": "info@democratsabroad.org", "Phone": "202-621-2085" },
    { "Name": "Adrianne R George", "State": "DA", "Email": "info@democratsabroad.org", "Phone": "202-621-2085" },
    { "Name": "Martha McDevitt-Pugh", "State": "DA", "Email": "info@democratsabroad.org", "Phone": "202-621-2085" },
    { "Name": "Art Schankler", "State": "DA", "Email": "info@democratsabroad.org", "Phone": "202-621-2085" },
    { "Name": "Kenneth E Sherman", "State": "DA", "Email": "info@democratsabroad.org", "Phone": "202-621-2085" },
    { "Name": "Orlando E Vidal", "State": "DA", "Email": "info@democratsabroad.org", "Phone": "202-621-2085" },
    { "Name": "Allison Tant", "State": "FL", "Email": "FDPinfo@fladems.com", "Phone": "850-222-3411" },
    { "Name": "Jon M Ausman", "State": "FL", "Email": "FDPinfo@fladems.com", "Phone": "850-222-3411" },
    { "Name": "Bret J Berlin", "State": "FL", "Email": "FDPinfo@fladems.com", "Phone": "850-222-3411" },
    { "Name": "Rick Boylan", "State": "FL", "Email": "FDPinfo@fladems.com", "Phone": "850-222-3411" },
    { "Name": "Mitchell Ceasar", "State": "FL", "Email": "FDPinfo@fladems.com", "Phone": "850-222-3411" },
    { "Name": "Alan R Clendenin", "State": "FL", "Email": "FDPinfo@fladems.com", "Phone": "850-222-3411" },
    { "Name": "Joyce Cusack", "State": "FL", "Email": "FDPinfo@fladems.com", "Phone": "850-222-3411" },
    { "Name": "Alma R Gonzalez", "State": "FL", "Email": "FDPinfo@fladems.com", "Phone": "850-222-3411" },
    { "Name": "Tony Hill", "State": "FL", "Email": "FDPinfo@fladems.com", "Phone": "850-222-3411" },
    { "Name": "Nancy C Jacobson", "State": "FL", "Email": "FDPinfo@fladems.com", "Phone": "850-222-3411" },
    { "Name": "Annette Taddeo-Goldstein", "State": "FL", "Email": "FDPinfo@fladems.com", "Phone": "850-222-3411" },
    { "Name": "Marian M Williams", "State": "FL", "Email": "FDPinfo@fladems.com", "Phone": "850-222-3411" },
    { "Name": "DuBose Porter", "State": "GA", "Email": "info@georgiademocrat.org", "Phone": "678-278-2016" },
    { "Name": "Wendy Davis", "State": "GA", "Email": "info@georgiademocrat.org", "Phone": "678-278-2016" },
    { "Name": "M Rahman", "State": "GA", "Email": "info@georgiademocrat.org", "Phone": "678-278-2016" },
    { "Name": "Richard A Ray", "State": "GA", "Email": "info@georgiademocrat.org", "Phone": "678-278-2016" },
    { "Name": "Sally S Rosser", "State": "GA", "Email": "info@georgiademocrat.org", "Phone": "678-278-2016" },
    { "Name": "Pamela Stephenson", "State": "GA", "Email": "info@georgiademocrat.org", "Phone": "678-278-2016" },
    { "Name": "Nikema Williams", "State": "GA", "Email": "info@georgiademocrat.org", "Phone": "678-278-2016" },
    { "Name": "Timothy A Vandeveer", "State": "HI", "Email": "info@hawaiidemocrats.org", "Phone": "808-596-2980" },
    { "Name": "Bart E Dame", "State": "HI", "Email": "info@hawaiidemocrats.org", "Phone": "808-596-2980" },
    { "Name": "Kathleen G Stanley", "State": "HI", "Email": "info@hawaiidemocrats.org", "Phone": "808-596-2980" },
    { "Name": "Marie Dolly Strazar", "State": "HI", "Email": "info@hawaiidemocrats.org", "Phone": "808-596-2980" },
    { "Name": "Bert C Marley", "State": "ID", "Email": "info@idahodems.org", "Phone": "208-336-1815" },
    { "Name": "Evangeline M Beechler", "State": "ID", "Email": "info@idahodems.org", "Phone": "208-336-1815" },
    { "Name": "Susan S Eastlake", "State": "ID", "Email": "info@idahodems.org", "Phone": "208-336-1815" },
    { "Name": "Jerry C Shriner", "State": "ID", "Email": "info@idahodems.org", "Phone": "208-336-1815" },
    { "Name": "Michael Madigan", "State": "IL", "Email": "contact@ildems.com", "Phone": "217-546-7404" },
    { "Name": "Carrie Austin", "State": "IL", "Email": "contact@ildems.com", "Phone": "217-546-7404" },
    { "Name": "Jerry F Costello", "State": "IL", "Email": "contact@ildems.com", "Phone": "217-546-7404" },
    { "Name": "John J Cullerton", "State": "IL", "Email": "contact@ildems.com", "Phone": "217-546-7404" },
    { "Name": "Danny K Davis", "State": "IL", "Email": "contact@ildems.com", "Phone": "217-546-7404" },
    { "Name": "Daniel W Hynes", "State": "IL", "Email": "contact@ildems.com", "Phone": "217-546-7404" },
    { "Name": "Iris Y Martinez", "State": "IL", "Email": "contact@ildems.com", "Phone": "217-546-7404" },
    { "Name": "Jayne Mazzotti", "State": "IL", "Email": "contact@ildems.com", "Phone": "217-546-7404" },
    { "Name": "Carol Ronen", "State": "IL", "Email": "contact@ildems.com", "Phone": "217-546-7404" },
    { "Name": "Karen A Yarbrough", "State": "IL", "Email": "contact@ildems.com", "Phone": "217-546-7404" },
    { "Name": "John C Zody", "State": "IN", "Email": "info@indems.org", "Phone": "317-231-7100" },
    { "Name": "David A Frye", "State": "IN", "Email": "info@indems.org", "Phone": "317-231-7100" },
    { "Name": "Cindy S Henry", "State": "IN", "Email": "info@indems.org", "Phone": "317-231-7100" },
    { "Name": "Cordelia M Lewis-Burks", "State": "IN", "Email": "info@indems.org", "Phone": "317-231-7100" },
    { "Name": "S. Anthony Long", "State": "IN", "Email": "info@indems.org", "Phone": "317-231-7100" },
    { "Name": "Andy H McGuire", "State": "IA", "Email": "info@iowademocrats.org", "Phone": "515-244-7292" },
    { "Name": "Scott M Brennan", "State": "IA", "Email": "info@iowademocrats.org", "Phone": "515-244-7292" },
    { "Name": "Danny Horman", "State": "IA", "Email": "info@iowademocrats.org", "Phone": "515-244-7292" },
    { "Name": "Sandy Opstvedt", "State": "IA", "Email": "info@iowademocrats.org", "Phone": "515-244-7292" },
    { "Name": "EL Kinch", "State": "KS", "Email": "info@kansasdems.org", "Phone": "785-234-0425" },
    { "Name": "Teresa Garcia Krusor", "State": "KS", "Email": "info@kansasdems.org", "Phone": "785-234-0425" },
    { "Name": "Melody McCray-Miller", "State": "KS", "Email": "info@kansasdems.org", "Phone": "785-234-0425" },
    { "Name": "Christopher T Reeves", "State": "KS", "Email": "info@kansasdems.org", "Phone": "785-234-0425" },
    { "Name": "Sannie Overly", "State": "KY", "Email": "info@kydemocrat.com", "Phone": "502-695-4828" },
    { "Name": "Neville Blakemore", "State": "KY", "Email": "info@kydemocrat.com", "Phone": "502-695-4828" },
    { "Name": "Charlotte Lundergan", "State": "KY", "Email": "info@kydemocrat.com", "Phone": "502-695-4828" },
    { "Name": "Nathan Gene Smith", "State": "KY", "Email": "info@kydemocrat.com", "Phone": "502-695-4828" },
    { "Name": "Karen Carter Peterson", "State": "LA", "Email": "info@lademo.org", "Phone": "225-336-4155" },
    { "Name": "Deborah J Langhoff", "State": "LA", "Email": "info@lademo.org", "Phone": "225-336-4155" },
    { "Name": "Michael McHale", "State": "LA", "Email": "info@lademo.org", "Phone": "225-336-4155" },
    { "Name": "Arthur Morell", "State": "LA", "Email": "info@lademo.org", "Phone": "225-336-4155" },
    { "Name": "Philip L Bartlett II", "State": "ME", "Email": "katiemae@mainedems.org", "Phone": "207-622-6233" },
    { "Name": "Diane M Denk", "State": "ME", "Email": "katiemae@mainedems.org", "Phone": "207-622-6233" },
    { "Name": "Troy Jackson", "State": "ME", "Email": "katiemae@mainedems.org", "Phone": "207-622-6233" },
    { "Name": "Peggy Schaffer", "State": "ME", "Email": "katiemae@mainedems.org", "Phone": "207-622-6233" },
    { "Name": "D Bruce Poole", "State": "MD", "Email": "info@mddems.org", "Phone": "410-269-8818" },
    { "Name": "Victoria Jackson-Stanley", "State": "MD", "Email": "info@mddems.org", "Phone": "410-269-8818" },
    { "Name": "Belkis (Bel) W Leong-Hong", "State": "MD", "Email": "info@mddems.org", "Phone": "410-269-8818" },
    { "Name": "Yvette W Lewis", "State": "MD", "Email": "info@mddems.org", "Phone": "410-269-8818" },
    { "Name": "Glenard S Middleton", "State": "MD", "Email": "info@mddems.org", "Phone": "410-269-8818" },
    { "Name": "Gregory Pecoraro", "State": "MD", "Email": "info@mddems.org", "Phone": "410-269-8818" },
    { "Name": "Thomas M McGee", "State": "MA", "Email": "contact@massdems.org", "Phone": "617-939-0800" },
    { "Name": "Gus Bickford", "State": "MA", "Email": "contact@massdems.org", "Phone": "617-939-0800" },
    { "Name": "Kate Donaghue", "State": "MA", "Email": "contact@massdems.org", "Phone": "617-939-0800" },
    { "Name": "Debra Kozikowski", "State": "MA", "Email": "contact@massdems.org", "Phone": "617-939-0800" },
    { "Name": "David M O'Brien", "State": "MA", "Email": "contact@massdems.org", "Phone": "617-939-0800" },
    { "Name": "Susan Thomson", "State": "MA", "Email": "contact@massdems.org", "Phone": "617-939-0800" },
    { "Name": "Brandon Dillon", "State": "MI", "Email": "midemparty@michigandems.com", "Phone": "517-371-5410" },
    { "Name": "Jill Alper", "State": "MI", "Email": "midemparty@michigandems.com", "Phone": "517-371-5410" },
    { "Name": "Steven B Cook", "State": "MI", "Email": "midemparty@michigandems.com", "Phone": "517-371-5410" },
    { "Name": "Debbie I Dingell", "State": "MI", "Email": "midemparty@michigandems.com", "Phone": "517-371-5410" },
    { "Name": "Albert Garrett", "State": "MI", "Email": "midemparty@michigandems.com", "Phone": "517-371-5410" },
    { "Name": "Barry J Goodman", "State": "MI", "Email": "midemparty@michigandems.com", "Phone": "517-371-5410" },
    { "Name": "Norwood Jewell", "State": "MI", "Email": "midemparty@michigandems.com", "Phone": "517-371-5410" },
    { "Name": "Nancy Quarles", "State": "MI", "Email": "midemparty@michigandems.com", "Phone": "517-371-5410" },
    { "Name": "Shauna Ryder Diggs", "State": "MI", "Email": "midemparty@michigandems.com", "Phone": "517-371-5410" },
    { "Name": "Ken Martin", "State": "MN", "Email": "info@dfl.org", "Phone": "651-293-1200" },
    { "Name": "James (JP) P Barone", "State": "MN", "Email": "info@dfl.org", "Phone": "651-293-1200" },
    { "Name": "Ron Harris", "State": "MN", "Email": "info@dfl.org", "Phone": "651-293-1200" },
    { "Name": "Marge Hoffa", "State": "MN", "Email": "info@dfl.org", "Phone": "651-293-1200" },
    { "Name": "Lori A Sellner", "State": "MN", "Email": "info@dfl.org", "Phone": "651-293-1200" },
    { "Name": "Elly Zaragoza", "State": "MN", "Email": "info@dfl.org", "Phone": "651-293-1200" },
    { "Name": "Bobby Moak", "State": "MS", "Email": "info@mississippidemocrats.org", "Phone": "601-969-2913" },
    { "Name": "Will Colom", "State": "MS", "Email": "info@mississippidemocrats.org", "Phone": "601-969-2913" },
    { "Name": "Raeshawn Davis", "State": "MS", "Email": "info@mississippidemocrats.org", "Phone": "601-969-2913" },
    { "Name": "Vicki R Slater", "State": "MS", "Email": "info@mississippidemocrats.org", "Phone": "601-969-2913" },
    { "Name": "Roy Temple", "State": "MO", "Email": "info@missouridems.org", "Phone": "573-636-5241" },
    { "Name": "(Gary) Winston Apple", "State": "MO", "Email": "info@missouridems.org", "Phone": "573-636-5241" },
    { "Name": "Persephone Dakopolos", "State": "MO", "Email": "info@missouridems.org", "Phone": "573-636-5241" },
    { "Name": "Megan E Green", "State": "MO", "Email": "info@missouridems.org", "Phone": "573-636-5241" },
    { "Name": "Darlene Green", "State": "MO", "Email": "info@missouridems.org", "Phone": "573-636-5241" },
    { "Name": "Curtis Wylde (Wells)", "State": "MO", "Email": "info@missouridems.org", "Phone": "573-636-5241" },
    { "Name": "Jim Larson", "State": "MT", "Email": "info@montanademocrats.org", "Phone": "406-442-9520" },
    { "Name": "Jacquie Helt", "State": "MT", "Email": "info@montanademocrats.org", "Phone": "406-442-9520" },
    { "Name": "Jean Lemire Dahlman", "State": "MT", "Email": "info@montanademocrats.org", "Phone": "406-442-9520" },
    { "Name": "Jorge Quintana", "State": "MT", "Email": "info@montanademocrats.org", "Phone": "406-442-9520" },
    { "Name": "Vince Powers*", "State": "NE", "Email": "info@nebraskademocrats.org", "Phone": "402-434-2180" },
    { "Name": "Ron Kaminski", "State": "NE", "Email": "info@nebraskademocrats.org", "Phone": "402-434-2180" },
    { "Name": "Maureen Monahan*", "State": "NE", "Email": "info@nebraskademocrats.org", "Phone": "402-434-2180" },
    { "Name": "Patricia A Zieg", "State": "NE", "Email": "info@nebraskademocrats.org", "Phone": "402-434-2180" },
    { "Name": "Jane Kleep", "State": "NE", "Email": "info@nebraskademocrats.org", "Phone": "402-434-2180" },
    { "Name": "Roberta A Lange", "State": "NV", "Email": "press@nvdems.com", "Phone": "702-737-8683" },
    { "Name": "Nelson Araujo", "State": "NV", "Email": "press@nvdems.com", "Phone": "702-737-8683" },
    { "Name": "Allison A Stephens", "State": "NV", "Email": "press@nvdems.com", "Phone": "702-737-8683" },
    { "Name": "Chris Wicker", "State": "NV", "Email": "press@nvdems.com", "Phone": "702-737-8683" },
    { "Name": "Martha Fuller Clark", "State": "NH", "Email": "office@nhdp.org", "Phone": "603-225-6899" },
    { "Name": "William H Shaheen", "State": "NH", "Email": "office@nhdp.org", "Phone": "603-225-6899" },
    { "Name": "Kathleen Sullivan", "State": "NH", "Email": "office@nhdp.org", "Phone": "603-225-6899" },
    { "Name": "John Currie", "State": "NJ", "Email": "info@njdems.org", "Phone": "609-392-3367" },
    { "Name": "Tonio Burgos", "State": "NJ", "Email": "info@njdems.org", "Phone": "609-392-3367" },
    { "Name": "Lizette Delgado Polanco", "State": "NJ", "Email": "info@njdems.org", "Phone": "609-392-3367" },
    { "Name": "John Graham", "State": "NJ", "Email": "info@njdems.org", "Phone": "609-392-3367" },
    { "Name": "Marcia Marley", "State": "NJ", "Email": "info@njdems.org", "Phone": "609-392-3367" },
    { "Name": "Bernadette P McPherson", "State": "NJ", "Email": "info@njdems.org", "Phone": "609-392-3367" },
    { "Name": "George E Norcross III", "State": "NJ", "Email": "info@njdems.org", "Phone": "609-392-3367" },
    { "Name": "Debra Haaland", "State": "NM", "Email": "info@nmdemocrats.org", "Phone": "505-830-3650" },
    { "Name": "Joni Marie Gutierrez", "State": "NM", "Email": "info@nmdemocrats.org", "Phone": "505-830-3650" },
    { "Name": "Juan Sanchez III", "State": "NM", "Email": "info@nmdemocrats.org", "Phone": "505-830-3650" },
    { "Name": "Raymond Sanchez", "State": "NM", "Email": "info@nmdemocrats.org", "Phone": "505-830-3650" },
    { "Name": "Byron Brown", "State": "NY", "Email": "nysdc@nydems.org", "Phone": "212-725-8825" },
    { "Name": "Stuart H Appelbaum", "State": "NY", "Email": "nysdc@nydems.org", "Phone": "212-725-8825" },
    { "Name": "Vivan Cook", "State": "NY", "Email": "nysdc@nydems.org", "Phone": "212-725-8825" },
    { "Name": "Jennifer Cunningham", "State": "NY", "Email": "nysdc@nydems.org", "Phone": "212-725-8825" },
    { "Name": "Maria Cuomo Cole", "State": "NY", "Email": "nysdc@nydems.org", "Phone": "212-725-8825" },
    { "Name": "Hazel Duke", "State": "NY", "Email": "nysdc@nydems.org", "Phone": "212-725-8825" },
    { "Name": "Herman Farrell Jr", "State": "NY", "Email": "nysdc@nydems.org", "Phone": "212-725-8825" },
    { "Name": "Emily Giske", "State": "NY", "Email": "nysdc@nydems.org", "Phone": "212-725-8825" },
    { "Name": "Carl Heastie", "State": "NY", "Email": "nysdc@nydems.org", "Phone": "212-725-8825" },
    { "Name": "Christine Quinn", "State": "NY", "Email": "nysdc@nydems.org", "Phone": "212-725-8825" },
    { "Name": "Michael Reich", "State": "NY", "Email": "nysdc@nydems.org", "Phone": "212-725-8825" },
    { "Name": "Gerald Sweeney", "State": "NY", "Email": "nysdc@nydems.org", "Phone": "212-725-8825" },
    { "Name": "Robert Zimmerman", "State": "NY", "Email": "nysdc@nydems.org", "Phone": "212-725-8825" },
    { "Name": "Patsy Keever", "State": "NC", "Email": "team@ncdp.org", "Phone": "919-821-2777" },
    { "Name": "Denise D Adams", "State": "NC", "Email": "team@ncdp.org", "Phone": "919-821-2777" },
    { "Name": "Ryan Butler", "State": "NC", "Email": "team@ncdp.org", "Phone": "919-821-2777" },
    { "Name": "Zack Hawkins", "State": "NC", "Email": "team@ncdp.org", "Phone": "919-821-2777" },
    { "Name": "Sheila A Huggins", "State": "NC", "Email": "team@ncdp.org", "Phone": "919-821-2777" },
    { "Name": "Cliff Moone", "State": "NC", "Email": "team@ncdp.org", "Phone": "919-821-2777" },
    { "Name": "John R Verdejo", "State": "NC", "Email": "team@ncdp.org", "Phone": "919-821-2777" },
    { "Name": "Kylie M Oversen", "State": "ND", "Email": "people@demnpl.com", "Phone": "701-255-0460" },
    { "Name": "Ondine E Baird", "State": "ND", "Email": "people@demnpl.com", "Phone": "701-255-0460" },
    { "Name": "Joshua A Boschee", "State": "ND", "Email": "people@demnpl.com", "Phone": "701-255-0460" },
    { "Name": "Warren D Larson", "State": "ND", "Email": "people@demnpl.com", "Phone": "701-255-0460" },
    { "Name": "David A Pepper", "State": "OH", "Email": "info@ohiodems.org", "Phone": "614-221-6563" },
    { "Name": "Tim Burga", "State": "OH", "Email": "info@ohiodems.org", "Phone": "614-221-6563" },
    { "Name": "Rebecca L Higgins", "State": "OH", "Email": "info@ohiodems.org", "Phone": "614-221-6563" },
    { "Name": "Mark Mallory", "State": "OH", "Email": "info@ohiodems.org", "Phone": "614-221-6563" },
    { "Name": "Ronald Malone", "State": "OH", "Email": "info@ohiodems.org", "Phone": "614-221-6563" },
    { "Name": "Valarie J McCall", "State": "OH", "Email": "info@ohiodems.org", "Phone": "614-221-6563" },
    { "Name": "Rhine McLin", "State": "OH", "Email": "info@ohiodems.org", "Phone": "614-221-6563" },
    { "Name": "Joe Rugola", "State": "OH", "Email": "info@ohiodems.org", "Phone": "614-221-6563" },
    { "Name": "Nina Turner", "State": "OH", "Email": "info@ohiodems.org", "Phone": "614-221-6563" },
    { "Name": "Mark Hammons", "State": "OK", "Email": "info@okdemocrats.org", "Phone": "405-427-3366" },
    { "Name": "Jim Frasier", "State": "OK", "Email": "info@okdemocrats.org", "Phone": "405-427-3366" },
    { "Name": "Connie Johnson", "State": "OK", "Email": "info@okdemocrats.org", "Phone": "405-427-3366" },
    { "Name": "Betty McElderry", "State": "OK", "Email": "info@okdemocrats.org", "Phone": "405-427-3366" },
    { "Name": "Frank Dixon", "State": "OR", "Email": "director@dpo.org", "Phone": "503-224-8200" },
    { "Name": "Laura E Calvo", "State": "OR", "Email": "director@dpo.org", "Phone": "503-224-8200" },
    { "Name": "Lupita Maurer", "State": "OR", "Email": "director@dpo.org", "Phone": "503-224-8200" },
    { "Name": "Karen A Packer", "State": "OR", "Email": "director@dpo.org", "Phone": "503-224-8200" },
    { "Name": "Larry Taylor", "State": "OR", "Email": "director@dpo.org", "Phone": "503-224-8200" },
    { "Name": "Marcel Groen", "State": "PA", "Email": "sincere@padems.com", "Phone": "717-920-8470" },
    { "Name": "Rick Bloomingdale", "State": "PA", "Email": "sincere@padems.com", "Phone": "717-920-8470" },
    { "Name": "Ronald Donatucci", "State": "PA", "Email": "sincere@padems.com", "Phone": "717-920-8470" },
    { "Name": "Penny Gerber", "State": "PA", "Email": "sincere@padems.com", "Phone": "717-920-8470" },
    { "Name": "Gerald Lawrence", "State": "PA", "Email": "sincere@padems.com", "Phone": "717-920-8470" },
    { "Name": "Nancy P Mills", "State": "PA", "Email": "sincere@padems.com", "Phone": "717-920-8470" },
    { "Name": "Ian Murray", "State": "PA", "Email": "sincere@padems.com", "Phone": "717-920-8470" },
    { "Name": "Evie Rafalko-McNulty", "State": "PA", "Email": "sincere@padems.com", "Phone": "717-920-8470" },
    { "Name": "Marian B Tasco", "State": "PA", "Email": "sincere@padems.com", "Phone": "717-920-8470" },
    { "Name": "Sylvia C Wilson", "State": "PA", "Email": "sincere@padems.com", "Phone": "717-920-8470" },
    { "Name": "Joseph McNamara", "State": "RI", "Email": "ridemocraticparty@gmail.com", "Phone": "401-272-3367" },
    { "Name": "Grace Diaz", "State": "RI", "Email": "ridemocraticparty@gmail.com", "Phone": "401-272-3367" },
    { "Name": "Frank Montanaro Sr", "State": "RI", "Email": "ridemocraticparty@gmail.com", "Phone": "401-272-3367" },
    { "Name": "Edna O'Neill Mattson", "State": "RI", "Email": "ridemocraticparty@gmail.com", "Phone": "401-272-3367" },
    { "Name": "Jaime R Harrison", "State": "SC", "Email": "info@scdp.org", "Phone": "803-799-7798" },
    { "Name": "Gilda Cobb-Hunter", "State": "SC", "Email": "info@scdp.org", "Phone": "803-799-7798" },
    { "Name": "Carol K Fowler", "State": "SC", "Email": "info@scdp.org", "Phone": "803-799-7798" },
    { "Name": "Kaye Lingle Koonce", "State": "SC", "Email": "info@scdp.org", "Phone": "803-799-7798" },
    { "Name": "Clay N Middleton", "State": "SC", "Email": "info@scdp.org", "Phone": "803-799-7798" },
    { "Name": "Ann Tornberg", "State": "SD", "Email": "info@sddp.org", "Phone": "605-271-5405" },
    { "Name": "Deb J Knecht", "State": "SD", "Email": "info@sddp.org", "Phone": "605-271-5405" },
    { "Name": "Joe Lowe", "State": "SD", "Email": "info@sddp.org", "Phone": "605-271-5405" },
    { "Name": "William E Walsh", "State": "SD", "Email": "info@sddp.org", "Phone": "605-271-5405" },
    { "Name": "Mary Mancini", "State": "TN", "Email": "hello@tndp.org", "Phone": "615-327-9779" },
    { "Name": "Gale Jones Carson", "State": "TN", "Email": "hello@tndp.org", "Phone": "615-327-9779" },
    { "Name": "Will T Cheek", "State": "TN", "Email": "hello@tndp.org", "Phone": "615-327-9779" },
    { "Name": "John H Litz", "State": "TN", "Email": "hello@tndp.org", "Phone": "615-327-9779" },
    { "Name": "William Owen", "State": "TN", "Email": "hello@tndp.org", "Phone": "615-327-9779" },
    { "Name": "Gilberto Hinojosa", "State": "TX", "Email": "crystal@txdemocrats.org", "Phone": "512-478-9800" },
    { "Name": "Yvonne Davis", "State": "TX", "Email": "crystal@txdemocrats.org", "Phone": "512-478-9800" },
    { "Name": "AJ Durrani", "State": "TX", "Email": "crystal@txdemocrats.org", "Phone": "512-478-9800" },
    { "Name": "Kat Hoang", "State": "TX", "Email": "crystal@txdemocrats.org", "Phone": "512-478-9800" },
    { "Name": "Glen Maxey", "State": "TX", "Email": "crystal@txdemocrats.org", "Phone": "512-478-9800" },
    { "Name": "John B Patrick", "State": "TX", "Email": "crystal@txdemocrats.org", "Phone": "512-478-9800" },
    { "Name": "Fredericka M Phillips", "State": "TX", "Email": "crystal@txdemocrats.org", "Phone": "512-478-9800" },
    { "Name": "Betty Z Richie", "State": "TX", "Email": "crystal@txdemocrats.org", "Phone": "512-478-9800" },
    { "Name": "Jose R Rodriguez", "State": "TX", "Email": "crystal@txdemocrats.org", "Phone": "512-478-9800" },
    { "Name": "Dennis D Speight", "State": "TX", "Email": "crystal@txdemocrats.org", "Phone": "512-478-9800" },
    { "Name": "Senfronia Thompson", "State": "TX", "Email": "crystal@txdemocrats.org", "Phone": "512-478-9800" },
    { "Name": "Celina Vasquez", "State": "TX", "Email": "crystal@txdemocrats.org", "Phone": "512-478-9800" },
    { "Name": "Royce B West", "State": "TX", "Email": "crystal@txdemocrats.org", "Phone": "512-478-9800" },
    { "Name": "Peter M Corroon", "State": "UT", "Email": "mail@utdem.org", "Phone": "801-328-1212" },
    { "Name": "Breanne Miller", "State": "UT", "Email": "mail@utdem.org", "Phone": "801-328-1212" },
    { "Name": "Charles A Stormont", "State": "UT", "Email": "mail@utdem.org", "Phone": "801-328-1212" },
    { "Name": "Jenny Wilson", "State": "UT", "Email": "mail@utdem.org", "Phone": "801-328-1212" },
    { "Name": "Dottie Deans", "State": "VT", "Email": "info@vtdemocrats.org", "Phone": "802-229-1783" },
    { "Name": "Terje Anderson", "State": "VT", "Email": "info@vtdemocrats.org", "Phone": "802-229-1783" },
    { "Name": "Tim Jerman", "State": "VT", "Email": "info@vtdemocrats.org", "Phone": "802-229-1783" },
    { "Name": "Mary M Sullivan", "State": "VT", "Email": "info@vtdemocrats.org", "Phone": "802-229-1783" },
    { "Name": "Susan R Swecker", "State": "VA", "Email": "info@vademocrats.org", "Phone": "804-644-1966" },
    { "Name": "Steven C Cochran", "State": "VA", "Email": "info@vademocrats.org", "Phone": "804-644-1966" },
    { "Name": "Doris Crouse-Mays", "State": "VA", "Email": "info@vademocrats.org", "Phone": "804-644-1966" },
    { "Name": "Fred W Hudson", "State": "VA", "Email": "info@vademocrats.org", "Phone": "804-644-1966" },
    { "Name": "Frank Leone", "State": "VA", "Email": "info@vademocrats.org", "Phone": "804-644-1966" },
    { "Name": "Atima Omara", "State": "VA", "Email": "info@vademocrats.org", "Phone": "804-644-1966" },
    { "Name": "Yasmine P Taeb", "State": "VA", "Email": "info@vademocrats.org", "Phone": "804-644-1966" },
    { "Name": "Jason Ravens", "State": "WA", "Email": "jaxon@wa-democrats.org", "Phone": "206-583-0664" },
    { "Name": "Ed Cote", "State": "WA", "Email": "jaxon@wa-democrats.org", "Phone": "206-583-0664" },
    { "Name": "Sharon Mast", "State": "WA", "Email": "jaxon@wa-democrats.org", "Phone": "206-583-0664" },
    { "Name": "David T McDonald", "State": "WA", "Email": "jaxon@wa-democrats.org", "Phone": "206-583-0664" },
    { "Name": "Nancy E Monacelli", "State": "WA", "Email": "jaxon@wa-democrats.org", "Phone": "206-583-0664" },
    { "Name": "Valerie Brady Rongey", "State": "WA", "Email": "jaxon@wa-democrats.org", "Phone": "206-583-0664" },
    { "Name": "Anita D Bonds", "State": "DC", "Email": "dcdemocraticparty@gmail.com", "Phone": "202-714-3368" },
    { "Name": "MaryEva Candon", "State": "DC", "Email": "dcdemocraticparty@gmail.com", "Phone": "202-714-3368" },
    { "Name": "Arrington Dixon", "State": "DC", "Email": "dcdemocraticparty@gmail.com", "Phone": "202-714-3368" },
    { "Name": "Ed Potillo", "State": "DC", "Email": "dcdemocraticparty@gmail.com", "Phone": "202-714-3368" },
    { "Name": "Belinda J Biafore", "State": "WV", "Email": "wvparty@wvdemocrats.com", "Phone": "304-342-8121" },
    { "Name": "Elaine A Harris", "State": "WV", "Email": "wvparty@wvdemocrats.com", "Phone": "304-342-8121" },
    { "Name": "William Laird", "State": "WV", "Email": "wvparty@wvdemocrats.com", "Phone": "304-342-8121" },
    { "Name": "Pat Maroney", "State": "WV", "Email": "wvparty@wvdemocrats.com", "Phone": "304-342-8121" },
    { "Name": "Martha K Laning", "State": "WI", "Email": "info@wisdems.org", "Phone": "608-255-5172" },
    { "Name": "Janet Bewley", "State": "WI", "Email": "info@wisdems.org", "Phone": "608-255-5172" },
    { "Name": "David Bowen", "State": "WI", "Email": "info@wisdems.org", "Phone": "608-255-5172" },
    { "Name": "Martha Marie Love", "State": "WI", "Email": "info@wisdems.org", "Phone": "608-255-5172" },
    { "Name": "Jason Rae", "State": "WI", "Email": "info@wisdems.org", "Phone": "608-255-5172" },
    { "Name": "Andrew Werthmann", "State": "WI", "Email": "info@wisdems.org", "Phone": "608-255-5172" },
    { "Name": "Ana Cuprill", "State": "WY", "Email": "info@wyodems.org", "Phone": "307-473-1457" },
    { "Name": "Jessica S Chambers", "State": "WY", "Email": "info@wyodems.org", "Phone": "307-473-1457" },
    { "Name": "Jon A Gardzelewski", "State": "WY", "Email": "info@wyodems.org", "Phone": "307-473-1457" },
    { "Name": "Bruce A Palmer", "State": "WY", "Email": "info@wyodems.org", "Phone": "307-473-1457" }
]
module.exports = electors;
