var electors = [{ "Name": "Donna Brazile", "Membership": "DNC officers", "State": "DC", "Phone": null, "Email": "", "Address": null },
    { "Name": "Maria Elena Durazo", "Membership": "DNC officers", "State": "CA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Grace Meng", "Membership": "DNC officers", "State": "NY", "Phone": null, "Email": "", "Address": null },
    { "Name": "R.T. Rybak", "Membership": "DNC officers", "State": "MN", "Phone": null, "Email": "", "Address": null },
    { "Name": "Raymond C Buckley II", "Membership": "DNC officers", "State": "NH", "Phone": null, "Email": "", "Address": null },
    { "Name": "Andrew Tobias", "Membership": "DNC officers", "State": "NY", "Phone": null, "Email": "", "Address": null },
    { "Name": "Stephanie Rawlings-Blake", "Membership": "DNC officers", "State": "MD", "Phone": null, "Email": "", "Address": null },
    { "Name": "Henry R Munoz III", "Membership": "DNC officers", "State": "TX", "Phone": null, "Email": "", "Address": null },
    { "Name": "Nancy L Worley", "Membership": "States- Alabama", "State": "AL", "Phone": null, "Email": "", "Address": null },
    { "Name": "Clinton M Daughtrey", "Membership": "States- Alabama", "State": "AL", "Phone": null, "Email": "", "Address": null },
    { "Name": "Greg Graves", "Membership": "States- Alabama", "State": "AL", "Phone": null, "Email": "", "Address": null },
    { "Name": "Randy B Kelley", "Membership": "States- Alabama", "State": "AL", "Phone": null, "Email": "", "Address": null },
    { "Name": "Janet May", "Membership": "States- Alabama", "State": "AL", "Phone": null, "Email": "", "Address": null },
    { "Name": "Casey Steinau", "Membership": "States- Alaska", "State": "AK", "Phone": "907-841-9830", "Email": "caseysteinau@gmail.com", "Address": null },
    { "Name": "Lawrence A Murakami", "Membership": "States- Alaska", "State": "AK", "Phone": "907-978-0260", "Email": "lamurakami@aol.com", "Address": null },
    { "Name": "Sheila A Selkregg", "Membership": "States- Alaska", "State": "AK", "Phone": "907-338-3636", "Email": "sheilaselkregg@ak.net", "Address": null },
    { "Name": "Edward Wesley", "Membership": "States- Alaska", "State": "AK", "Phone": "907-350-0419", "Email": "ejfw@gci.net", "Address": null },
    { "Name": "M Tuufuli Galeai", "Membership": "States- American Samoa", "State": "AS", "Phone": null, "Email": "", "Address": null },
    { "Name": "Therese L Hunkin", "Membership": "States- American Samoa", "State": "AS", "Phone": null, "Email": "", "Address": null },
    { "Name": "Fagafaga D Langkilde", "Membership": "States- American Samoa", "State": "AS", "Phone": null, "Email": "", "Address": null },
    { "Name": "Clara Reid", "Membership": "States- American Samoa", "State": "AS", "Phone": null, "Email": "", "Address": null },
    { "Name": "Alexis C Tameron", "Membership": "States- Arizona", "State": "AZ", "Phone": "602-298-4200", "Email": "chair@azdem.org", "Address": null },
    { "Name": "Douglas Ballard", "Membership": "States- Arizona", "State": "AZ", "Phone": "480-993-8841", "Email": "dougb@ccdem.org", "Address": null },
    { "Name": "Luis Heredia", "Membership": "States- Arizona", "State": "AZ", "Phone": null, "Email": "luis.heredia@gmail.com", "Address": null },
    { "Name": "William G Roe", "Membership": "States- Arizona", "State": "AZ", "Phone": "602-298-4200", "Email": "broe@azdem.org", "Address": null },
    { "Name": "Carolyn Warner", "Membership": "States- Arizona", "State": "AZ", "Phone": "602-957-7552", "Email": "cwarner@carolynwarner.com", "Address": null },
    { "Name": "Vincent Insalaco", "Membership": "States- Arkansas", "State": "AR", "Phone": null, "Email": "chair@arkdems.org", "Address": null },
    { "Name": "Joyce Elliott", "Membership": "States- Arkansas", "State": "AR", "Phone": null, "Email": "vicechair1@arkdems.org", "Address": null },
    { "Name": "Dustin McDaniel", "Membership": "States- Arkansas", "State": "AR", "Phone": null, "Email": "nationalcommitteeman@arkdems.org", "Address": null },
    { "Name": "Kasey Summerville", "Membership": "States- Arkansas", "State": "AR", "Phone": null, "Email": "nationalcommitteewoman@arkdems.org", "Address": null },
    { "Name": "John Burton", "Membership": "States- California", "State": "CA", "Phone": null, "Email": "john@cadem.org", "Address": null },
    { "Name": "Steven K Alari", "Membership": "States- California", "State": "CA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Becca Doten", "Membership": "States- California", "State": "CA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Jesse Durfee", "Membership": "States- California", "State": "CA", "Phone": null, "Email": "jess@jessdurfee.com", "Address": null },
    { "Name": "Mary Ellen Early", "Membership": "States- California", "State": "CA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Alexandra Gallardo Rooker", "Membership": "States- California", "State": "CA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Alice A Huffman", "Membership": "States- California", "State": "CA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Aleita J Huguenin", "Membership": "States- California", "State": "CA", "Phone": null, "Email": "Aleita4DNC@aol.com", "Address": null },
    { "Name": "Michael Kapp", "Membership": "States- California", "State": "CA", "Phone": null, "Email": "mdkapp@gmail.com", "Address": null },
    { "Name": "Andrew Lachman", "Membership": "States- California", "State": "CA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Barbara Lee", "Membership": "States- California", "State": "CA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Otto O Lee", "Membership": "States- California", "State": "CA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Sandra M Lowe", "Membership": "States- California", "State": "CA", "Phone": null, "Email": "smarchele@yahoo.com", "Address": null },
    { "Name": "Bob Mulholland", "Membership": "States- California", "State": "CA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Christie Pelosi", "Membership": "States- California", "State": "CA", "Phone": null, "Email": "sfpelosi@yahoo.com", "Address": null },
    { "Name": "John A Perez", "Membership": "States- California", "State": "CA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Melahat Rafiei", "Membership": "States- California", "State": "CA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Susie A Shannon", "Membership": "States- California", "State": "CA", "Phone": null, "Email": "susieanneshannon@gmail.com", "Address": null },
    { "Name": "Garry S Shay", "Membership": "States- California", "State": "CA", "Phone": null, "Email": "gss1@aol.com", "Address": null },
    { "Name": "Keith Umemoto", "Membership": "States- California", "State": "CA", "Phone": null, "Email": "kumemoto@att.net", "Address": null },
    { "Name": "Maxine Waters", "Membership": "States- California", "State": "CA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Laurence S Zakson", "Membership": "States- California", "State": "CA", "Phone": null, "Email": "zaksonfordnc@gmail.com", "Address": null },
    { "Name": "Rick A Palacio", "Membership": "States- Colorado", "State": "CO", "Phone": null, "Email": "", "Address": null },
    { "Name": "Michael F Hamrick", "Membership": "States- Colorado", "State": "CO", "Phone": null, "Email": "", "Address": null },
    { "Name": "Beverly Benavidez Ryken", "Membership": "States- Colorado", "State": "CO", "Phone": null, "Email": "bryken@coloradodems.org", "Address": null },
    { "Name": "Jeri D Shepherd", "Membership": "States- Colorado", "State": "CO", "Phone": null, "Email": "", "Address": null },
    { "Name": "Terry L Tucker", "Membership": "States- Colorado", "State": "CO", "Phone": null, "Email": "", "Address": null },
    { "Name": "Dominic F Balletto Jr", "Membership": "States- Connecticut", "State": "CT", "Phone": null, "Email": "nballetto@ctdems.org", "Address": null },
    { "Name": "Nancy DiNardo", "Membership": "States- Connecticut", "State": "CT", "Phone": null, "Email": "ndinardo@ctdems.org", "Address": null },
    { "Name": "John W Olsen", "Membership": "States- Connecticut", "State": "CT", "Phone": null, "Email": "", "Address": null },
    { "Name": "John D Daniello", "Membership": "States- Delaware", "State": "DE", "Phone": "302-540-9822", "Email": "", "Address": null },
    { "Name": "Robert Gilligan", "Membership": "States- Delaware", "State": "DE", "Phone": "302-999-8722", "Email": "", "Address": null },
    { "Name": "Lisa B Goodman", "Membership": "States- Delaware", "State": "DE", "Phone": "302-633-6680", "Email": "", "Address": null },
    { "Name": "Karen Lynne Kirkpatrick-Valentine", "Membership": "States- Delaware", "State": "DE", "Phone": "302-697-9708", "Email": "", "Address": null },
    { "Name": "Katie Solon", "Membership": "States- Democrats Abroad (1/2 vote each)", "State": "DA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Connie Borde", "Membership": "States- Democrats Abroad (1/2 vote each)", "State": "DA", "Phone": null, "Email": "", "Address": null },
    { "Name": "John A Eastwood", "Membership": "States- Democrats Abroad (1/2 vote each)", "State": "DA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Adrianne R George", "Membership": "States- Democrats Abroad (1/2 vote each)", "State": "DA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Martha McDevitt-Pugh", "Membership": "States- Democrats Abroad (1/2 vote each)", "State": "DA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Art Schankler", "Membership": "States- Democrats Abroad (1/2 vote each)", "State": "DA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Kenneth E Sherman", "Membership": "States- Democrats Abroad (1/2 vote each)", "State": "DA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Orlando E Vidal", "Membership": "States- Democrats Abroad (1/2 vote each)", "State": "DA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Allison Tant", "Membership": "States- Florida", "State": "FL", "Phone": null, "Email": "", "Address": null },
    { "Name": "Jon M Ausman", "Membership": "States- Florida", "State": "FL", "Phone": null, "Email": "", "Address": null },
    { "Name": "Bret J Berlin", "Membership": "States- Florida", "State": "FL", "Phone": null, "Email": "", "Address": null },
    { "Name": "Rick Boylan", "Membership": "States- Florida", "State": "FL", "Phone": null, "Email": "", "Address": null },
    { "Name": "Mitchell Ceasar", "Membership": "States- Florida", "State": "FL", "Phone": null, "Email": "", "Address": null },
    { "Name": "Alan R Clendenin", "Membership": "States- Florida", "State": "FL", "Phone": null, "Email": "", "Address": null },
    { "Name": "Joyce Cusack", "Membership": "States- Florida", "State": "FL", "Phone": null, "Email": "", "Address": null },
    { "Name": "Alma R Gonzalez", "Membership": "States- Florida", "State": "FL", "Phone": null, "Email": "", "Address": null },
    { "Name": "Tony Hill", "Membership": "States- Florida", "State": "FL", "Phone": null, "Email": "", "Address": null },
    { "Name": "Nancy C Jacobson", "Membership": "States- Florida", "State": "FL", "Phone": null, "Email": "", "Address": null },
    { "Name": "Annette Taddeo-Goldstein", "Membership": "States- Florida", "State": "FL", "Phone": null, "Email": "", "Address": null },
    { "Name": "Marian M Williams", "Membership": "States- Florida", "State": "FL", "Phone": null, "Email": "", "Address": null },
    { "Name": "DuBose Porter", "Membership": "States- Georgia", "State": "GA", "Phone": null, "Email": "DuBose@georgiademocrat.org", "Address": null },
    { "Name": "Wendy Davis", "Membership": "States- Georgia", "State": "GA", "Phone": null, "Email": "?? Website has diff info", "Address": null },
    { "Name": "M Rahman", "Membership": "States- Georgia", "State": "GA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Richard A Ray", "Membership": "States- Georgia", "State": "GA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Sally S Rosser", "Membership": "States- Georgia", "State": "GA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Pamela Stephenson", "Membership": "States- Georgia", "State": "GA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Nikema Williams", "Membership": "States- Georgia", "State": "GA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Joaquin Perez", "Membership": "States- Guam", "State": "GU", "Phone": null, "Email": "", "Address": null },
    { "Name": "Rory Respicio", "Membership": "States- Guam", "State": "GU", "Phone": null, "Email": "", "Address": null },
    { "Name": "Taling Taitano", "Membership": "States- Guam", "State": "GU", "Phone": null, "Email": "", "Address": null },
    { "Name": "Sarah Thomas-Nededog", "Membership": "States- Guam", "State": "GU", "Phone": null, "Email": "", "Address": null },
    { "Name": "Timothy A Vandeveer", "Membership": "States- Hawaii", "State": "HI", "Phone": null, "Email": "", "Address": null },
    { "Name": "Bart E Dame", "Membership": "States- Hawaii", "State": "HI", "Phone": null, "Email": "", "Address": null },
    { "Name": "Kathleen G Stanley", "Membership": "States- Hawaii", "State": "HI", "Phone": null, "Email": "", "Address": null },
    { "Name": "Marie Dolly Strazar", "Membership": "States- Hawaii", "State": "HI", "Phone": null, "Email": "", "Address": null },
    { "Name": "Bert C Marley", "Membership": "States- Idaho", "State": "ID", "Phone": "208-406-6785", "Email": "bmarley1948@gmail.com", "Address": null },
    { "Name": "Evangeline M Beechler", "Membership": "States- Idaho", "State": "ID", "Phone": null, "Email": "ebeechler@gmail.com", "Address": null },
    { "Name": "Susan S Eastlake", "Membership": "States- Idaho", "State": "ID", "Phone": null, "Email": "sseast1@gmail.com", "Address": null },
    { "Name": "Jerry C Shriner", "Membership": "States- Idaho", "State": "ID", "Phone": null, "Email": "jerryshriner@gmail.com", "Address": null },
    { "Name": "Michael Madigan", "Membership": "States- Illinois", "State": "IL", "Phone": null, "Email": "", "Address": null },
    { "Name": "Carrie Austin", "Membership": "States- Illinois", "State": "IL", "Phone": null, "Email": "", "Address": null },
    { "Name": "Jerry F Costello", "Membership": "States- Illinois", "State": "IL", "Phone": null, "Email": "", "Address": null },
    { "Name": "John J Cullerton", "Membership": "States- Illinois", "State": "IL", "Phone": null, "Email": "", "Address": null },
    { "Name": "Danny K Davis", "Membership": "States- Illinois", "State": "IL", "Phone": null, "Email": "", "Address": null },
    { "Name": "Daniel W Hynes", "Membership": "States- Illinois", "State": "IL", "Phone": null, "Email": "", "Address": null },
    { "Name": "Iris Y Martinez", "Membership": "States- Illinois", "State": "IL", "Phone": null, "Email": "", "Address": null },
    { "Name": "Jayne Mazzotti", "Membership": "States- Illinois", "State": "IL", "Phone": null, "Email": "", "Address": null },
    { "Name": "Carol Ronen", "Membership": "States- Illinois", "State": "IL", "Phone": null, "Email": "", "Address": null },
    { "Name": "Karen A Yarbrough", "Membership": "States- Illinois", "State": "IL", "Phone": null, "Email": "", "Address": null },
    { "Name": "John C Zody", "Membership": "States- Indiana", "State": "IN", "Phone": null, "Email": "jzody@indems.org", "Address": null },
    { "Name": "David A Frye", "Membership": "States- Indiana", "State": "IN", "Phone": null, "Email": "dfryeinldc@aol.com", "Address": null },
    { "Name": "Cindy S Henry", "Membership": "States- Indiana", "State": "IN", "Phone": null, "Email": "tchenry1975@comcast.net", "Address": null },
    { "Name": "Cordelia M Lewis-Burks", "Membership": "States- Indiana", "State": "IN", "Phone": null, "Email": "clewisburks1237@gmail.com", "Address": null },
    { "Name": "S. Anthony Long", "Membership": "States- Indiana", "State": "IN", "Phone": null, "Email": "demochair@gmail.com", "Address": null },
    { "Name": "Andy H McGuire", "Membership": "States- Iowa", "State": "IA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Scott M Brennan", "Membership": "States- Iowa", "State": "IA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Danny Horman", "Membership": "States- Iowa", "State": "IA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Sandy Opstvedt", "Membership": "States- Iowa", "State": "IA", "Phone": null, "Email": "", "Address": null },
    { "Name": "EL Kinch", "Membership": "States- Kansas", "State": "KS", "Phone": null, "Email": "", "Address": null },
    { "Name": "Teresa Garcia Krusor", "Membership": "States- Kansas", "State": "KS", "Phone": null, "Email": "", "Address": null },
    { "Name": "Melody McCray-Miller", "Membership": "States- Kansas", "State": "KS", "Phone": null, "Email": "", "Address": null },
    { "Name": "Christopher T Reeves", "Membership": "States- Kansas", "State": "KS", "Phone": null, "Email": "", "Address": null },
    { "Name": "Sannie Overly", "Membership": "States- Kentucky", "State": "KY", "Phone": null, "Email": "", "Address": null },
    { "Name": "Neville Blakemore", "Membership": "States- Kentucky", "State": "KY", "Phone": null, "Email": "", "Address": null },
    { "Name": "Charlotte Lundergan", "Membership": "States- Kentucky", "State": "KY", "Phone": null, "Email": "", "Address": null },
    { "Name": "Nathan Gene Smith", "Membership": "States- Kentucky", "State": "KY", "Phone": null, "Email": "", "Address": null },
    { "Name": "Karen Carter Peterson", "Membership": "States- Louisiana", "State": "LA", "Phone": "504-599-8664", "Email": "", "Address": null },
    { "Name": "Deborah J Langhoff", "Membership": "States- Louisiana", "State": "LA", "Phone": "504-259-4525", "Email": "", "Address": null },
    { "Name": "Michael McHale", "Membership": "States- Louisiana", "State": "LA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Arthur Morell", "Membership": "States- Louisiana", "State": "LA", "Phone": "504-658-9000", "Email": "", "Address": null },
    { "Name": "Philip L Bartlett II", "Membership": "States- Maine", "State": "ME", "Phone": null, "Email": "phil@philbartlett.com", "Address": null },
    { "Name": "Diane M Denk", "Membership": "States- Maine", "State": "ME", "Phone": null, "Email": "peggylschaffer@gmail.com", "Address": null },
    { "Name": "Troy Jackson", "Membership": "States- Maine", "State": "ME", "Phone": null, "Email": "jacksonforsenate@hotmail.com ", "Address": null },
    { "Name": "Peggy Schaffer", "Membership": "States- Maine", "State": "ME", "Phone": null, "Email": "denkhansen@gmail.com", "Address": null },
    { "Name": "D Bruce Poole", "Membership": "States- Maryland", "State": "MD", "Phone": null, "Email": "", "Address": null },
    { "Name": "Victoria Jackson-Stanley", "Membership": "States- Maryland", "State": "MD", "Phone": null, "Email": "", "Address": null },
    { "Name": "Belkis (Bel) W Leong-Hong", "Membership": "States- Maryland", "State": "MD", "Phone": null, "Email": "", "Address": null },
    { "Name": "Yvette W Lewis", "Membership": "States- Maryland", "State": "MD", "Phone": null, "Email": "", "Address": null },
    { "Name": "Glenard S Middleton", "Membership": "States- Maryland", "State": "MD", "Phone": null, "Email": "", "Address": null },
    { "Name": "Gregory Pecoraro", "Membership": "States- Maryland", "State": "MD", "Phone": null, "Email": "", "Address": null },
    { "Name": "Thomas M McGee", "Membership": "States- Massachusetts", "State": "MA", "Phone": null, "Email": "tmcgee@massdems.org", "Address": null },
    { "Name": "Gus Bickford", "Membership": "States- Massachusetts", "State": "MA", "Phone": null, "Email": "gus@factotumproductions.com", "Address": null },
    { "Name": "Kate Donaghue", "Membership": "States- Massachusetts", "State": "MA", "Phone": null, "Email": "katedonaghue@aol.com", "Address": null },
    { "Name": "Debra Kozikowski", "Membership": "States- Massachusetts", "State": "MA", "Phone": null, "Email": "debbyskoz@cs.com", "Address": null },
    { "Name": "David M O'Brien", "Membership": "States- Massachusetts", "State": "MA", "Phone": null, "Email": "tripdirector@yahoo.com", "Address": null },
    { "Name": "Susan Thomson", "Membership": "States- Massachusetts", "State": "MA", "Phone": null, "Email": "scthomson@live.com", "Address": null },
    { "Name": "Brandon Dillon", "Membership": "States- Michigan", "State": "MI", "Phone": null, "Email": "", "Address": null },
    { "Name": "Jill Alper", "Membership": "States- Michigan", "State": "MI", "Phone": null, "Email": "", "Address": null },
    { "Name": "Steven B Cook", "Membership": "States- Michigan", "State": "MI", "Phone": null, "Email": "", "Address": null },
    { "Name": "Debbie I Dingell", "Membership": "States- Michigan", "State": "MI", "Phone": null, "Email": "", "Address": null },
    { "Name": "Albert Garrett", "Membership": "States- Michigan", "State": "MI", "Phone": null, "Email": "", "Address": null },
    { "Name": "Barry J Goodman", "Membership": "States- Michigan", "State": "MI", "Phone": null, "Email": "", "Address": null },
    { "Name": "Norwood Jewell", "Membership": "States- Michigan", "State": "MI", "Phone": null, "Email": "", "Address": null },
    { "Name": "Nancy Quarles", "Membership": "States- Michigan", "State": "MI", "Phone": null, "Email": "", "Address": null },
    { "Name": "Shauna Ryder Diggs", "Membership": "States- Michigan", "State": "MI", "Phone": null, "Email": "", "Address": null },
    { "Name": "Ken Martin", "Membership": "States- Minnesota", "State": "MN", "Phone": null, "Email": "", "Address": null },
    { "Name": "James (JP) P Barone", "Membership": "States- Minnesota", "State": "MN", "Phone": null, "Email": "", "Address": null },
    { "Name": "Ron Harris", "Membership": "States- Minnesota", "State": "MN", "Phone": null, "Email": "", "Address": null },
    { "Name": "Marge Hoffa", "Membership": "States- Minnesota", "State": "MN", "Phone": null, "Email": "", "Address": null },
    { "Name": "Lori A Sellner", "Membership": "States- Minnesota", "State": "MN", "Phone": null, "Email": "", "Address": null },
    { "Name": "Elly Zaragoza", "Membership": "States- Minnesota", "State": "MN", "Phone": null, "Email": "", "Address": null },
    { "Name": "Bobby Moak", "Membership": "States- Mississippi", "State": "MS", "Phone": null, "Email": "", "Address": null },
    { "Name": "Will Colom", "Membership": "States- Mississippi", "State": "MS", "Phone": null, "Email": "", "Address": null },
    { "Name": "Raeshawn Davis", "Membership": "States- Mississippi", "State": "MS", "Phone": null, "Email": "", "Address": null },
    { "Name": "Vicki R Slater", "Membership": "States- Mississippi", "State": "MS", "Phone": null, "Email": "", "Address": null },
    { "Name": "Roy Temple", "Membership": "States- Missouri", "State": "MO", "Phone": null, "Email": "", "Address": null },
    { "Name": "(Gary) Winston Apple", "Membership": "States- Missouri", "State": "MO", "Phone": null, "Email": "", "Address": null },
    { "Name": "Persephone Dakopolos", "Membership": "States- Missouri", "State": "MO", "Phone": null, "Email": "", "Address": null },
    { "Name": "Megan E Green", "Membership": "States- Missouri", "State": "MO", "Phone": null, "Email": "", "Address": null },
    { "Name": "Darlene Green", "Membership": "States- Missouri", "State": "MO", "Phone": null, "Email": "", "Address": null },
    { "Name": "Curtis Wylde (Wells)", "Membership": "States- Missouri", "State": "MO", "Phone": null, "Email": "", "Address": null },
    { "Name": "Jim Larson", "Membership": "States- Montana", "State": "MT", "Phone": null, "Email": "", "Address": null },
    { "Name": "Jacquie Helt", "Membership": "States- Montana", "State": "MT", "Phone": null, "Email": "", "Address": null },
    { "Name": "Jean Lemire Dahlman", "Membership": "States- Montana", "State": "MT", "Phone": null, "Email": "", "Address": null },
    { "Name": "Jorge Quintana", "Membership": "States- Montana", "State": "MT", "Phone": null, "Email": "", "Address": null },
    { "Name": "Vince Powers*", "Membership": "States- Nebraska", "State": "NE", "Phone": null, "Email": "", "Address": null },
    { "Name": "Ron Kaminski", "Membership": "States- Nebraska", "State": "NE", "Phone": "402-573-7878", "Email": "ronald@laborers1140.org", "Address": null },
    { "Name": "Maureen Monahan*", "Membership": "States- Nebraska", "State": "NE", "Phone": null, "Email": "", "Address": null },
    { "Name": "Patricia A Zieg", "Membership": "States- Nebraska", "State": "NE", "Phone": "402-740-9904", "Email": "patty@nebraskademocrats.org", "Address": null },
    { "Name": "Jane Kleep", "Membership": "States- Nebraska", "State": "NE", "Phone": "402-705-3622", "Email": "janekleeb@gmail.com", "Address": null },
    { "Name": "Roberta A Lange", "Membership": "States- Nevada", "State": "NV", "Phone": null, "Email": "", "Address": null },
    { "Name": "Nelson Araujo", "Membership": "States- Nevada", "State": "NV", "Phone": null, "Email": "", "Address": null },
    { "Name": "Allison A Stephens", "Membership": "States- Nevada", "State": "NV", "Phone": null, "Email": "", "Address": null },
    { "Name": "Chris Wicker", "Membership": "States- Nevada", "State": "NV", "Phone": null, "Email": "", "Address": null },
    { "Name": "Martha Fuller Clark", "Membership": "States- New Hampshire", "State": "NH", "Phone": null, "Email": "", "Address": "New Hampshire Democratic Party" },
    { "Name": "William H Shaheen", "Membership": "States- New Hampshire", "State": "NH", "Phone": null, "Email": "", "Address": "105 N. State Street" },
    { "Name": "Kathleen Sullivan", "Membership": "States- New Hampshire", "State": "NH", "Phone": null, "Email": "", "Address": "Concord, NH 03301" },
    { "Name": "John Currie", "Membership": "States- New Jersey", "State": "NJ", "Phone": null, "Email": "", "Address": "New Jersey Democratic State Committee" },
    { "Name": "Tonio Burgos", "Membership": "States- New Jersey", "State": "NJ", "Phone": null, "Email": "", "Address": "194-196 West State Street" },
    { "Name": "Lizette Delgado Polanco", "Membership": "States- New Jersey", "State": "NJ", "Phone": null, "Email": "", "Address": "Trenton, NJ 08608" },
    { "Name": "John Graham", "Membership": "States- New Jersey", "State": "NJ", "Phone": null, "Email": "", "Address": null },
    { "Name": "Marcia Marley", "Membership": "States- New Jersey", "State": "NJ", "Phone": null, "Email": "", "Address": null },
    { "Name": "Bernadette P McPherson", "Membership": "States- New Jersey", "State": "NJ", "Phone": null, "Email": "", "Address": null },
    { "Name": "George E Norcross III", "Membership": "States- New Jersey", "State": "NJ", "Phone": null, "Email": "", "Address": null },
    { "Name": "Debra Haaland", "Membership": "States- New Mexico", "State": "NM", "Phone": null, "Email": "deb@nmdemocrats.org", "Address": "322 Adams St. SE" },
    { "Name": "Joni Marie Gutierrez", "Membership": "States- New Mexico", "State": "NM", "Phone": null, "Email": "jonig@zianet.com", "Address": "Albuquerque, NM 87108" },
    { "Name": "Juan Sanchez III", "Membership": "States- New Mexico", "State": "NM", "Phone": null, "Email": "juan.sanchez@nmdemocrats.org", "Address": null },
    { "Name": "Raymond Sanchez", "Membership": "States- New Mexico", "State": "NM", "Phone": null, "Email": "rgsanchez@smdlegal.com", "Address": null },
    { "Name": "Byron Brown", "Membership": "States- New York", "State": "NY", "Phone": null, "Email": "", "Address" : "750 Third Avenue, 31st Floor, New York, NY 10017" },
    { "Name": "Stuart H Appelbaum", "Membership": "States- New York", "State": "NY", "Phone": null, "Email": "", "Address": null },
    { "Name": "Vivan Cook", "Membership": "States- New York", "State": "NY", "Phone": null, "Email": "", "Address": null },
    { "Name": "Jennifer Cunningham", "Membership": "States- New York", "State": "NY", "Phone": null, "Email": "", "Address": null },
    { "Name": "Maria Cuomo Cole", "Membership": "States- New York", "State": "NY", "Phone": null, "Email": "", "Address": null },
    { "Name": "Hazel Duke", "Membership": "States- New York", "State": "NY", "Phone": null, "Email": "", "Address": null },
    { "Name": "Herman Farrell Jr", "Membership": "States- New York", "State": "NY", "Phone": null, "Email": "", "Address": null },
    { "Name": "Emily Giske", "Membership": "States- New York", "State": "NY", "Phone": null, "Email": "", "Address": null },
    { "Name": "Carl Heastie", "Membership": "States- New York", "State": "NY", "Phone": null, "Email": "", "Address": null },
    { "Name": "Christine Quinn", "Membership": "States- New York", "State": "NY", "Phone": null, "Email": "", "Address": null },
    { "Name": "Michael Reich", "Membership": "States- New York", "State": "NY", "Phone": null, "Email": "", "Address": null },
    { "Name": "Gerald Sweeney", "Membership": "States- New York", "State": "NY", "Phone": null, "Email": "", "Address": null },
    { "Name": "Robert Zimmerman", "Membership": "States- New York", "State": "NY", "Phone": null, "Email": "", "Address": null },
    { "Name": "Patsy Keever", "Membership": "States- North Carolina", "State": "NC", "Phone": null, "Email": "PatsyKeever@ncdp.org", "Address": null },
    { "Name": "Denise D Adams", "Membership": "States- North Carolina", "State": "NC", "Phone": null, "Email": "dadams34@triad.rr.com", "Address": null },
    { "Name": "Ryan Butler", "Membership": "States- North Carolina", "State": "NC", "Phone": null, "Email": "rtb@ryanbutler.net", "Address": null },
    { "Name": "Zack Hawkins", "Membership": "States- North Carolina", "State": "NC", "Phone": null, "Email": "zackhawkins@ncdp.org", "Address": null },
    { "Name": "Sheila A Huggins", "Membership": "States- North Carolina", "State": "NC", "Phone": null, "Email": "shannhu@aol.com", "Address": null },
    { "Name": "Cliff Moone", "Membership": "States- North Carolina", "State": "NC", "Phone": null, "Email": "moonesmark@gmail.com", "Address": null },
    { "Name": "John R Verdejo", "Membership": "States- North Carolina", "State": "NC", "Phone": null, "Email": "jrverdejo@gmail.com", "Address": null },
    { "Name": "Kylie M Oversen", "Membership": "States- North Dakota", "State": "ND", "Phone": null, "Email": "", "Address": null },
    { "Name": "Ondine E Baird", "Membership": "States- North Dakota", "State": "ND", "Phone": null, "Email": "", "Address": null },
    { "Name": "Joshua A Boschee", "Membership": "States- North Dakota", "State": "ND", "Phone": null, "Email": "", "Address": null },
    { "Name": "Warren D Larson", "Membership": "States- North Dakota", "State": "ND", "Phone": null, "Email": "", "Address": null },
    { "Name": "Daniel Quitugua", "Membership": "States- Northern Mariana Islands", "State": "NMI", "Phone": null, "Email": "", "Address": null },
    { "Name": "Emelia S Chargualaf", "Membership": "States- Northern Mariana Islands", "State": "NMI", "Phone": null, "Email": "", "Address": null },
    { "Name": "Nola Hix", "Membership": "States- Northern Mariana Islands", "State": "NMI", "Phone": null, "Email": "", "Address": null },
    { "Name": "Herbert D Soll", "Membership": "States- Northern Mariana Islands", "State": "NMI", "Phone": null, "Email": "", "Address": null },
    { "Name": "David A Pepper", "Membership": "States- Ohio", "State": "OH", "Phone": null, "Email": "", "Address": null },
    { "Name": "Tim Burga", "Membership": "States- Ohio", "State": "OH", "Phone": null, "Email": "", "Address": null },
    { "Name": "Rebecca L Higgins", "Membership": "States- Ohio", "State": "OH", "Phone": null, "Email": "", "Address": null },
    { "Name": "Mark Mallory", "Membership": "States- Ohio", "State": "OH", "Phone": null, "Email": "", "Address": null },
    { "Name": "Ronald Malone", "Membership": "States- Ohio", "State": "OH", "Phone": null, "Email": "", "Address": null },
    { "Name": "Valarie J McCall", "Membership": "States- Ohio", "State": "OH", "Phone": null, "Email": "", "Address": null },
    { "Name": "Rhine McLin", "Membership": "States- Ohio", "State": "OH", "Phone": null, "Email": "", "Address": null },
    { "Name": "Joe Rugola", "Membership": "States- Ohio", "State": "OH", "Phone": null, "Email": "", "Address": null },
    { "Name": "Nina Turner", "Membership": "States- Ohio", "State": "OH", "Phone": null, "Email": "", "Address": null },
    { "Name": "Mark Hammons", "Membership": "States- Oklahoma", "State": "OK", "Phone": null, "Email": "", "Address": null },
    { "Name": "Jim Frasier", "Membership": "States- Oklahoma", "State": "OK", "Phone": null, "Email": "", "Address": null },
    { "Name": "Connie Johnson", "Membership": "States- Oklahoma", "State": "OK", "Phone": null, "Email": "", "Address": null },
    { "Name": "Betty McElderry", "Membership": "States- Oklahoma", "State": "OK", "Phone": null, "Email": "", "Address": null },
    { "Name": "Frank Dixon", "Membership": "States- Oregon", "State": "OR", "Phone": null, "Email": "", "Address": null },
    { "Name": "Laura E Calvo", "Membership": "States- Oregon", "State": "OR", "Phone": null, "Email": "", "Address": null },
    { "Name": "Lupita Maurer", "Membership": "States- Oregon", "State": "OR", "Phone": null, "Email": "", "Address": null },
    { "Name": "Karen A Packer", "Membership": "States- Oregon", "State": "OR", "Phone": null, "Email": "", "Address": null },
    { "Name": "Larry Taylor", "Membership": "States- Oregon", "State": "OR", "Phone": null, "Email": "", "Address": null },
    { "Name": "Marcel Groen", "Membership": "States- Pennsylvania", "State": "PA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Rick Bloomingdale", "Membership": "States- Pennsylvania", "State": "PA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Ronald Donatucci", "Membership": "States- Pennsylvania", "State": "PA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Penny Gerber", "Membership": "States- Pennsylvania", "State": "PA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Gerald Lawrence", "Membership": "States- Pennsylvania", "State": "PA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Nancy P Mills", "Membership": "States- Pennsylvania", "State": "PA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Ian Murray", "Membership": "States- Pennsylvania", "State": "PA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Evie Rafalko-McNulty", "Membership": "States- Pennsylvania", "State": "PA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Marian B Tasco", "Membership": "States- Pennsylvania", "State": "PA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Sylvia C Wilson", "Membership": "States- Pennsylvania", "State": "PA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Roberto L Prats", "Membership": "States- Puerto Rico", "State": "PR", "Phone": null, "Email": "", "Address": null },
    { "Name": "Kenneth D McClintock", "Membership": "States- Puerto Rico", "State": "PR", "Phone": null, "Email": "", "Address": null },
    { "Name": "Gina Mendez", "Membership": "States- Puerto Rico", "State": "PR", "Phone": null, "Email": "", "Address": null },
    { "Name": "Liza M Ortiz", "Membership": "States- Puerto Rico", "State": "PR", "Phone": null, "Email": "", "Address": null },
    { "Name": "Joseph McNamara", "Membership": "States- Rhode Island", "State": "RI", "Phone": null, "Email": "", "Address": null },
    { "Name": "Grace Diaz", "Membership": "States- Rhode Island", "State": "RI", "Phone": null, "Email": "", "Address": null },
    { "Name": "Frank Montanaro Sr", "Membership": "States- Rhode Island", "State": "RI", "Phone": null, "Email": "", "Address": null },
    { "Name": "Edna O'Neill Mattson", "Membership": "States- Rhode Island", "State": "RI", "Phone": null, "Email": "", "Address": null },
    { "Name": "Jaime R Harrison", "Membership": "States- South Carolina", "State": "SC", "Phone": null, "Email": "", "Address": null },
    { "Name": "Gilda Cobb-Hunter", "Membership": "States- South Carolina", "State": "SC", "Phone": null, "Email": "", "Address": null },
    { "Name": "Carol K Fowler", "Membership": "States- South Carolina", "State": "SC", "Phone": null, "Email": "", "Address": null },
    { "Name": "Kaye Lingle Koonce", "Membership": "States- South Carolina", "State": "SC", "Phone": null, "Email": "", "Address": null },
    { "Name": "Clay N Middleton", "Membership": "States- South Carolina", "State": "SC", "Phone": null, "Email": "", "Address": null },
    { "Name": "Ann Tornberg", "Membership": "States- South Dakota", "State": "SD", "Phone": null, "Email": "", "Address": null },
    { "Name": "Deb J Knecht", "Membership": "States- South Dakota", "State": "SD", "Phone": null, "Email": "", "Address": null },
    { "Name": "Joe Lowe", "Membership": "States- South Dakota", "State": "SD", "Phone": null, "Email": "", "Address": null },
    { "Name": "William E Walsh", "Membership": "States- South Dakota", "State": "SD", "Phone": null, "Email": "", "Address": null },
    { "Name": "Mary Mancini", "Membership": "States- Tennessee", "State": "TN", "Phone": null, "Email": "", "Address": null },
    { "Name": "Gale Jones Carson", "Membership": "States- Tennessee", "State": "TN", "Phone": null, "Email": "", "Address": null },
    { "Name": "Will T Cheek", "Membership": "States- Tennessee", "State": "TN", "Phone": null, "Email": "", "Address": null },
    { "Name": "John H Litz", "Membership": "States- Tennessee", "State": "TN", "Phone": null, "Email": "", "Address": null },
    { "Name": "William Owen", "Membership": "States- Tennessee", "State": "TN", "Phone": null, "Email": "", "Address": null },
    { "Name": "Gilberto Hinojosa", "Membership": "States- Texas", "State": "TX", "Phone": null, "Email": "", "Address": null },
    { "Name": "Yvonne Davis", "Membership": "States- Texas", "State": "TX", "Phone": null, "Email": "", "Address": null },
    { "Name": "AJ Durrani", "Membership": "States- Texas", "State": "TX", "Phone": null, "Email": "", "Address": null },
    { "Name": "Kat Hoang", "Membership": "States- Texas", "State": "TX", "Phone": null, "Email": "", "Address": null },
    { "Name": "Glen Maxey", "Membership": "States- Texas", "State": "TX", "Phone": null, "Email": "", "Address": null },
    { "Name": "John B Patrick", "Membership": "States- Texas", "State": "TX", "Phone": null, "Email": "", "Address": null },
    { "Name": "Fredericka M Phillips", "Membership": "States- Texas", "State": "TX", "Phone": null, "Email": "", "Address": null },
    { "Name": "Betty Z Richie", "Membership": "States- Texas", "State": "TX", "Phone": null, "Email": "", "Address": null },
    { "Name": "Jose R Rodriguez", "Membership": "States- Texas", "State": "TX", "Phone": null, "Email": "", "Address": null },
    { "Name": "Dennis D Speight", "Membership": "States- Texas", "State": "TX", "Phone": null, "Email": "", "Address": null },
    { "Name": "Senfronia Thompson", "Membership": "States- Texas", "State": "TX", "Phone": null, "Email": "", "Address": null },
    { "Name": "Celina Vasquez", "Membership": "States- Texas", "State": "TX", "Phone": null, "Email": "", "Address": null },
    { "Name": "Royce B West", "Membership": "States- Texas", "State": "TX", "Phone": null, "Email": "", "Address": null },
    { "Name": "Peter M Corroon", "Membership": "States- Utah", "State": "UT", "Phone": null, "Email": "", "Address": null },
    { "Name": "Breanne Miller", "Membership": "States- Utah", "State": "UT", "Phone": null, "Email": "", "Address": null },
    { "Name": "Charles A Stormont", "Membership": "States- Utah", "State": "UT", "Phone": null, "Email": "", "Address": null },
    { "Name": "Jenny Wilson", "Membership": "States- Utah", "State": "UT", "Phone": null, "Email": "", "Address": null },
    { "Name": "Dottie Deans", "Membership": "States- Vermont", "State": "VT", "Phone": null, "Email": "", "Address": null },
    { "Name": "Terje Anderson", "Membership": "States- Vermont", "State": "VT", "Phone": null, "Email": "", "Address": null },
    { "Name": "Tim Jerman", "Membership": "States- Vermont", "State": "VT", "Phone": null, "Email": "", "Address": null },
    { "Name": "Mary M Sullivan", "Membership": "States- Vermont", "State": "VT", "Phone": null, "Email": "", "Address": null },
    { "Name": "Donna M Christensen", "Membership": "States- Virgin Islands", "State": "VI", "Phone": null, "Email": "", "Address": null },
    { "Name": "Carol M Burke", "Membership": "States- Virgin Islands", "State": "VI", "Phone": null, "Email": "", "Address": null },
    { "Name": "Luis ", "Membership": "States- Virgin Islands", "State": "VI", "Phone": null, "Email": "", "Address": null },
    { "Name": "Glen Smith", "Membership": "States- Virgin Islands", "State": "VI", "Phone": null, "Email": "", "Address": null },
    { "Name": "Susan R Swecker", "Membership": "States- Virginia", "State": "VA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Steven C Cochran", "Membership": "States- Virginia", "State": "VA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Doris Crouse-Mays", "Membership": "States- Virginia", "State": "VA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Fred W Hudson", "Membership": "States- Virginia", "State": "VA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Frank Leone", "Membership": "States- Virginia", "State": "VA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Atima Omara", "Membership": "States- Virginia", "State": "VA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Yasmine P Taeb", "Membership": "States- Virginia", "State": "VA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Jason Ravens", "Membership": "States- Washington", "State": "WA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Ed Cote", "Membership": "States- Washington", "State": "WA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Sharon Mast", "Membership": "States- Washington", "State": "WA", "Phone": null, "Email": "", "Address": null },
    { "Name": "David T McDonald", "Membership": "States- Washington", "State": "WA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Nancy E Monacelli", "Membership": "States- Washington", "State": "WA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Valerie Brady Rongey", "Membership": "States- Washington", "State": "WA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Anita D Bonds", "Membership": "States- District of Columbia", "State": "DC", "Phone": null, "Email": "", "Address": null },
    { "Name": "MaryEva Candon", "Membership": "States- District of Columbia", "State": "DC", "Phone": null, "Email": "", "Address": null },
    { "Name": "Arrington Dixon", "Membership": "States- District of Columbia", "State": "DC", "Phone": null, "Email": "", "Address": null },
    { "Name": "Ed Potillo", "Membership": "States- District of Columbia", "State": "DC", "Phone": null, "Email": "", "Address": null },
    { "Name": "Belinda J Biafore", "Membership": "States- West Virginia", "State": "WV", "Phone": null, "Email": "", "Address": null },
    { "Name": "Elaine A Harris", "Membership": "States- West Virginia", "State": "WV", "Phone": null, "Email": "", "Address": null },
    { "Name": "William Laird", "Membership": "States- West Virginia", "State": "WV", "Phone": null, "Email": "", "Address": null },
    { "Name": "Pat Maroney", "Membership": "States- West Virginia", "State": "WV", "Phone": null, "Email": "", "Address": null },
    { "Name": "Martha K Laning", "Membership": "States- Wisconsin", "State": "WI", "Phone": null, "Email": "", "Address": null },
    { "Name": "Janet Bewley", "Membership": "States- Wisconsin", "State": "WI", "Phone": null, "Email": "", "Address": null },
    { "Name": "David Bowen", "Membership": "States- Wisconsin", "State": "WI", "Phone": null, "Email": "", "Address": null },
    { "Name": "Martha Marie Love", "Membership": "States- Wisconsin", "State": "WI", "Phone": null, "Email": "", "Address": null },
    { "Name": "Jason Rae", "Membership": "States- Wisconsin", "State": "WI", "Phone": null, "Email": "", "Address": null },
    { "Name": "Andrew Werthmann", "Membership": "States- Wisconsin", "State": "WI", "Phone": null, "Email": "", "Address": null },
    { "Name": "Ana Cuprill", "Membership": "States- Wyoming", "State": "WY", "Phone": null, "Email": "", "Address": null },
    { "Name": "Jessica S Chambers", "Membership": "States- Wyoming", "State": "WY", "Phone": null, "Email": "", "Address": null },
    { "Name": "Jon A Gardzelewski", "Membership": "States- Wyoming", "State": "WY", "Phone": null, "Email": "", "Address": null },
    { "Name": "Bruce A Palmer", "Membership": "States- Wyoming", "State": "WY", "Phone": null, "Email": "", "Address": null },
    { "Name": "Karl A Racine", "Membership": "Groups- Attorneys General", "State": "DC", "Phone": null, "Email": "", "Address": null },
    { "Name": "Ellen Rosenblum", "Membership": "Groups- Attorneys General", "State": "CO", "Phone": null, "Email": "", "Address": null },
    { "Name": "Marv B McMoore Jr", "Membership": "Groups- College Democrats of America", "State": "NY", "Phone": null, "Email": "", "Address": null },
    { "Name": "Ellen R Lindblom", "Membership": "Groups- College Democrats of America", "State": "MI", "Phone": null, "Email": "", "Address": null },
    { "Name": "Nancy Pelosi", "Membership": "Groups- Congress", "State": "CA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Harry Reid", "Membership": "Groups- Congress", "State": "NV", "Phone": null, "Email": "", "Address": null },
    { "Name": "Gregory Meeks", "Membership": "Groups- Congress", "State": "NY", "Phone": null, "Email": "", "Address": null },
    { "Name": "Debbie Stabenow", "Membership": "Groups- Congress", "State": "MI", "Phone": null, "Email": "", "Address": null },
    { "Name": "Arlanda Williams", "Membership": "Groups- County officials", "State": "LA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Unzell Kelly", "Membership": "Groups- County officials", "State": "AL", "Phone": null, "Email": "", "Address": null },
    { "Name": "Bruce A Morrison", "Membership": "Groups- Ethnic Coordinating Committee", "State": "MD", "Phone": null, "Email": "", "Address": null },
    { "Name": "Danica R Oparnica", "Membership": "Groups- Ethnic Coordinating Committee", "State": "AZ", "Phone": null, "Email": "", "Address": null },
    { "Name": "Joanne Sullivan", "Membership": "Groups- Federation of Democratic Women", "State": "CT", "Phone": null, "Email": "", "Address": null },
    { "Name": "Maureen A McKenna", "Membership": "Groups- Federation of Democratic Women", "State": "Unknown", "Phone": null, "Email": "", "Address": null },
    { "Name": "Virgie M Rollins", "Membership": "Groups- Federation of Democratic Women", "State": "MI", "Phone": null, "Email": "", "Address": null },
    { "Name": "Steve Bullock", "Membership": "Groups- Governors association", "State": "MT", "Phone": null, "Email": "", "Address": null },
    { "Name": "Maggie Hassan", "Membership": "Groups- Governors association", "State": "NH", "Phone": null, "Email": "", "Address": null },
    { "Name": "Dan Malloy", "Membership": "Groups- Governors association", "State": "CT", "Phone": null, "Email": "", "Address": null },
    { "Name": "Michael Gronstal", "Membership": "Groups- Legislative Campaign Committee", "State": "IA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Garnet Coleman", "Membership": "Groups- Legislative Campaign Committee", "State": "TX", "Phone": null, "Email": "", "Address": null },
    { "Name": "Valerie Longhurst", "Membership": "Groups- Legislative Campaign Committee", "State": "DE", "Phone": null, "Email": "", "Address": null },
    { "Name": "Shan Tsutsui", "Membership": "Groups- Lieutenant Governors", "State": "HI", "Phone": null, "Email": "", "Address": null },
    { "Name": "Nancy Wyman", "Membership": "Groups- Lieutenant Governors", "State": "CT", "Phone": null, "Email": "", "Address": null },
    { "Name": "Sly James", "Membership": "Groups- Mayors", "State": "MO", "Phone": null, "Email": "", "Address": null },
    { "Name": "Eric Garcetti", "Membership": "Groups- Mayors", "State": "CA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Nan Whaley", "Membership": "Groups- Mayors", "State": "OH", "Phone": null, "Email": "", "Address": null },
    { "Name": "Joe A. Buscaino", "Membership": "Groups- Municipal", "State": "CA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Susie Nakasian", "Membership": "Groups- Municipal", "State": "Unknown", "Phone": null, "Email": "", "Address": null },
    { "Name": "Gregory S Pettis", "Membership": "Groups- Municipal", "State": "CA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Natalie Tennant", "Membership": "Groups- Secretaries of State", "State": "WV", "Phone": null, "Email": "", "Address": null },
    { "Name": "Jim Condos", "Membership": "Groups- Secretaries of State", "State": "VT", "Phone": null, "Email": "", "Address": null },
    { "Name": "Steve Regenstreif", "Membership": "Groups- Seniors Coordinating Council", "State": "DC", "Phone": null, "Email": "", "Address": null },
    { "Name": "Maria C Cordone", "Membership": "Groups- Seniors Coordinating Council", "State": "MD", "Phone": null, "Email": "", "Address": null },
    { "Name": "Janet Cowell", "Membership": "Groups- State Treasurers", "State": "ND", "Phone": null, "Email": "", "Address": null },
    { "Name": "John Perdue", "Membership": "Groups- State Treasurers", "State": "WV", "Phone": null, "Email": "", "Address": null },
    { "Name": "Louis Elrod", "Membership": "Groups- Young Democrats of America", "State": "GA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Akilah Ensley", "Membership": "Groups- Young Democrats of America", "State": "ND", "Phone": null, "Email": "", "Address": null },
    { "Name": "John A Keller", "Membership": "Groups- Young Democrats of America", "State": "IL", "Phone": null, "Email": "", "Address": null },
    { "Name": "Rafael Anchia", "Membership": "At-large", "State": "TX", "Phone": null, "Email": "", "Address": null },
    { "Name": "Dennis Archer", "Membership": "At-large", "State": "MI", "Phone": null, "Email": "", "Address": null },
    { "Name": "Virginia Barnes", "Membership": "At-large", "State": "MA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Jan Bauer", "Membership": "At-large", "State": "IA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Jeff Berman", "Membership": "At-large", "State": "DC", "Phone": null, "Email": "", "Address": null },
    { "Name": "Stephen Bittel", "Membership": "At-large", "State": "FL", "Phone": null, "Email": "", "Address": null },
    { "Name": "Artie Blanco", "Membership": "At-large", "State": "NV", "Phone": null, "Email": "", "Address": null },
    { "Name": "James Boland", "Membership": "At-large", "State": "DC", "Phone": null, "Email": "", "Address": null },
    { "Name": "Joyce Brayboy", "Membership": "At-large", "State": "DC", "Phone": null, "Email": "", "Address": null },
    { "Name": "Laphonza Butler", "Membership": "At-large", "State": "Unknown", "Phone": null, "Email": "", "Address": null },
    { "Name": "Maria Cardona", "Membership": "At-large", "State": "DC", "Phone": null, "Email": "", "Address": null },
    { "Name": "James Clayborne", "Membership": "At-large", "State": "IL", "Phone": null, "Email": "", "Address": null },
    { "Name": "Tony Coelho", "Membership": "At-large", "State": "DE", "Phone": null, "Email": "", "Address": null },
    { "Name": "Larry Cohen", "Membership": "At-large", "State": "Unknown", "Phone": null, "Email": "", "Address": null },
    { "Name": "J. David Cox", "Membership": "At-large", "State": "DC", "Phone": null, "Email": "", "Address": null },
    { "Name": "Leah Daughtry", "Membership": "At-large", "State": "DC", "Phone": null, "Email": "", "Address": null },
    { "Name": "Ralph Dawson", "Membership": "At-large", "State": "NY", "Phone": null, "Email": "", "Address": null },
    { "Name": "Barbaralee Diamonstein-Spielvogel", "Membership": "At-large", "State": "NY", "Phone": null, "Email": "", "Address": null },
    { "Name": "Joanne Dowdell", "Membership": "At-large", "State": "DC", "Phone": null, "Email": "", "Address": null },
    { "Name": "Maria Echaveste", "Membership": "At-large", "State": "CA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Lily Eskelsen Garcia", "Membership": "At-large", "State": "DC", "Phone": null, "Email": "", "Address": null },
    { "Name": "Joseph Falk", "Membership": "At-large", "State": "FL", "Phone": null, "Email": "", "Address": null },
    { "Name": "Katherine Fernandez Rundle", "Membership": "At-large", "State": "FL", "Phone": null, "Email": "", "Address": null },
    { "Name": "Raj Fernando", "Membership": "At-large", "State": "IL", "Phone": null, "Email": "", "Address": null },
    { "Name": "Hector Figueroa", "Membership": "At-large", "State": "NY", "Phone": null, "Email": "", "Address": null },
    { "Name": "Donald Lionel Fowler", "Membership": "At-large", "State": "SC", "Phone": null, "Email": "", "Address": null },
    { "Name": "Isabel Framer", "Membership": "At-large", "State": "Unknown", "Phone": null, "Email": "", "Address": null },
    { "Name": "Montserrat Garibay", "Membership": "At-large", "State": "TX", "Phone": null, "Email": "", "Address": null },
    { "Name": "Tefere Gebre", "Membership": "At-large", "State": "MD", "Phone": null, "Email": "", "Address": null },
    { "Name": "Alice T Germond", "Membership": "At-large", "State": "CA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Angel Gomez", "Membership": "At-large", "State": "Unknown", "Phone": null, "Email": "", "Address": null },
    { "Name": "Amanda Green-Hawkins", "Membership": "At-large", "State": "PA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Janice Griffin", "Membership": "At-large", "State": "Unknown", "Phone": null, "Email": "", "Address": null },
    { "Name": "Carol Guthrie", "Membership": "At-large", "State": "Unknown", "Phone": null, "Email": "", "Address": null },
    { "Name": "Daniel Halpern", "Membership": "At-large", "State": "GA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Harold Ickes", "Membership": "At-large", "State": "DC", "Phone": null, "Email": "", "Address": null },
    { "Name": "Jay Jacobs", "Membership": "At-large", "State": "NY", "Phone": null, "Email": "", "Address": null },
    { "Name": "Matthew Johnson", "Membership": "At-large", "State": "CA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Lacy Johnson", "Membership": "At-large", "State": "IN", "Phone": null, "Email": "", "Address": null },
    { "Name": "Elaine C Kamarck", "Membership": "At-large", "State": "MA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Sarah Kovner", "Membership": "At-large", "State": "NY", "Phone": null, "Email": "", "Address": null },
    { "Name": "Sunita Leeds", "Membership": "At-large", "State": "DC", "Phone": null, "Email": "", "Address": null },
    { "Name": "Andres Lopez", "Membership": "At-large", "State": "PR", "Phone": null, "Email": "", "Address": null },
    { "Name": "Evan Low", "Membership": "At-large", "State": "CA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Juanita G Luiz", "Membership": "At-large", "State": "WA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Kerman Maddox", "Membership": "At-large", "State": "CA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Marcus Mason", "Membership": "At-large", "State": "DC", "Phone": null, "Email": "", "Address": null },
    { "Name": "Jennifer L McClellan", "Membership": "At-large", "State": "VA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Mattie McFadden-Lawson", "Membership": "At-large", "State": "CA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Lorraine C Miller", "Membership": "At-large", "State": "Unknown", "Phone": null, "Email": "", "Address": null },
    { "Name": "Minyon Moore", "Membership": "At-large", "State": "DC", "Phone": null, "Email": "", "Address": null },
    { "Name": "Michael A. Nutter", "Membership": "At-large", "State": "PA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Blanca Uzeta O'Leary", "Membership": "At-large", "State": "CO", "Phone": null, "Email": "", "Address": null },
    { "Name": "Carlos Odio", "Membership": "At-large", "State": "FL", "Phone": null, "Email": "", "Address": null },
    { "Name": "Carol J Pensky", "Membership": "At-large", "State": "DC", "Phone": null, "Email": "", "Address": null },
    { "Name": "Steven M Powell", "Membership": "At-large", "State": "IL", "Phone": null, "Email": "", "Address": null },
    { "Name": "Carrie Pugh", "Membership": "At-large", "State": "DC", "Phone": null, "Email": "", "Address": null },
    { "Name": "Andres Ramirez Jr.", "Membership": "At-large", "State": "NV", "Phone": null, "Email": "", "Address": null },
    { "Name": "Rion J Ramirez", "Membership": "At-large", "State": "Unknown", "Phone": null, "Email": "", "Address": null },
    { "Name": "Kasim Reed", "Membership": "At-large", "State": "GA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Laura Ricketts", "Membership": "At-large", "State": "IL", "Phone": null, "Email": "", "Address": null },
    { "Name": "James Roosevelt Jr.", "Membership": "At-large", "State": "MA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Lee A Saunders", "Membership": "At-large", "State": "DC", "Phone": null, "Email": "", "Address": null },
    { "Name": "Lottie Shackelford", "Membership": "At-large", "State": "AR", "Phone": null, "Email": "", "Address": null },
    { "Name": "Barbra ", "Membership": "At-large", "State": "Unknown", "Phone": null, "Email": "", "Address": null },
    { "Name": "Hilda L Solis", "Membership": "At-large", "State": "CA", "Phone": null, "Email": "", "Address": null },
    { "Name": "Rick C. Wade", "Membership": "At-large", "State": "DC", "Phone": null, "Email": "", "Address": null },
    { "Name": "Brian Wahby", "Membership": "At-large", "State": "MO", "Phone": null, "Email": "", "Address": null },
    { "Name": "Randi Weingarten", "Membership": "At-large", "State": "DC", "Phone": null, "Email": "", "Address": null },
    { "Name": "Alan Williams", "Membership": "At-large", "State": "Unknown", "Phone": null, "Email": "", "Address": null },
    { "Name": "James J Zogby", "Membership": "At-large", "State": "DC", "Phone": null, "Email": "", "Address": null }
];

module.exports = electors;
