var states = [{"State":"Alabama","Name":"Alabama Democrats","Line1":"P.O. Box 950","Line2":"","Line3":"Montgomery, AL 36101"},
{"State":"Alaska","Name":"Alaska Democratic Party","Line1":"2602 Fairbanks st.","Line2":"","Line3":"Anchorage, AK 99503"},
{"State":"Arizona","Name":"Arizona Democratic Party","Line1":"2910 North Central Ave","Line2":"","Line3":"Phoenix, AZ 85012"},
{"State":"Arkansas","Name":"Arkansas Democrats","Line1":"1300 West Capital Ave.","Line2":"","Line3":"Little Rock, AR 72201"},
{"State":"California","Name":"California Democratic Party","Line1":"1830 9th Street","Line2":"","Line3":"Sacramento, CA 95811"},
{"State":"Colorado","Name":"Colorado Democratic Party","Line1":"789 Sherman St","Line2":"Suite 110","Line3":"Denver, CO 80203"},
{"State":"Connecticut","Name":"Connecticut Democratic Party","Line1":"30 Arbor Street","Line2":"Suite 404","Line3":"Hartford, CT 06106"},
{"State":"Delaware","Name":"Delaware Democratic Party","Line1":"P.O. BOX 2065","Line2":"","Line3":"Wilmington, DE 19899"},
{"State":"Democrats Abroad","Name":"Democrats Abroad DPCA","Line1":"PO Box 15130","Line2":"","Line3":"Washington, DC 20003, USA"},
{"State":"Florida","Name":"Florida Democratic Party","Line1":"214 S Bronough St","Line2":"","Line3":"Tallahassee, FL 32301"},
{"State":"Georgia","Name":"Democratic Party of Georgia","Line1":"501 Pulliam St.","Line2":"Suite 400","Line3":"Atlanta, GA 30312"},
{"State":"Hawaii","Name":"Democratic Party of Hawaii","Line1":"PO Box 2041 ","Line2":"","Line3":"Honolulu, HI 96805-2041"},
{"State":"Idaho","Name":"Idaho Democratic Party","Line1":"812 W Franklin St","Line2":"","Line3":"Boise, ID 83701"},
{"State":"Illinois","Name":"Democratic Party of Illinois","Line1":"PO Box 518","Line2":"","Line3":"Springfield, IL 62705"},
{"State":"Indiani","Name":"Indiana Democratic Party","Line1":"115 W. Washington Street","Line2":"Suite 1165","Line3":"Indianapolis, IN 46204"},
{"State":"Iowa","Name":"Iowa Democratic Party","Line1":"5661 Fleur Drive","Line2":"","Line3":"Des Moines, IA 50321"},
{"State":"Kansas","Name":"Kansas Democratic Party","Line1":"501 SE Jefferson st","Line2":"Suite 30","Line3":"Topeka, KS 66607"},
{"State":"Kentucky","Name":"Kentucky Democratic Party","Line1":"PO Box 694","Line2":"","Line3":"Frankfort, KY 40602"},
{"State":"Louisiana","Name":"Louisiana Democratic Party","Line1":"PO Box 4385","Line2":"","Line3":"Baton Rouge, LA 70821"},
{"State":"Maine","Name":"Maine Democratic Party","Line1":"320 Water Street","Line2":"3rd Floor","Line3":"Augusta, ME 04330"},
{"State":"Maryland","Name":"Maryland Democratic Party","Line1":"33 West Street","Line2":"Suite 200","Line3":"Annapolis, MD 21401"},
{"State":"Massachusetts","Name":"Massachusetts Democratic Party","Line1":"11 Beacon St","Line2":"Suite 410","Line3":"Boston, MA 02108"},
{"State":"Michigan","Name":"Michigan Democratic Party","Line1":"606 Townsend","Line2":"","Line3":"Lansing, MI 48933"},
{"State":"Minnesota","Name":"Minnesota DFL Party Headquarters","Line1":"255 East Plato Blvd.","Line2":"","Line3":"St. Paul, MN 55107"},
{"State":"Mississippi","Name":"Mississippi Democratic Party","Line1":"PO Box 1583","Line2":"","Line3":"Jackson, MS 39215"},
{"State":"Missouri","Name":"Missouri Democratic Party","Line1":"PO Box 719","Line2":"","Line3":"Jefferson City, MO 65101"},
{"State":"Montana","Name":"Montana Democratic Party","Line1":"PO Box 802","Line2":"","Line3":"Helena, MT 59624"},
{"State":"Nebraska","Name":"Nebraska Democratic Party","Line1":"201 N 8th St","Line2":"Suite 210","Line3":"Lincoln, NE 68508"},
{"State":"Nevada","Name":"Nevada State Democratic Party","Line1":"6233 Dean Martin Drive","Line2":"","Line3":"Las Vegas, NV 89118"},
{"State":"New Hampshire","Name":"New Hampshire Democratic Party","Line1":"105 N. State Street","Line2":"","Line3":"Concord, NH 03301"},
{"State":"New Jersey","Name":"New Jersey Democratic State Committee","Line1":"194-196 West State Street","Line2":"","Line3":"Trenton, NJ 08608"},
{"State":"New Mexico","Name":"Democratic Party of New Mexico","Line1":"322 Adams St. SE","Line2":"","Line3":"Albuquerque, NM 87108"},
{"State":"New York","Name":"New York State Democratic Party","Line1":"750 Third Avenue","Line2":"31st Floor","Line3":"New York, NY 10017"},
{"State":"North Carolina","Name":"North Carolina Democratic Party","Line1":"PO Box 1926","Line2":"","Line3":"Raleigh, NC 27602"},
{"State":"North Dakota","Name":"North Dakota Democratic-NPL","Line1":"1902 East Divide Avenue","Line2":"Kennedy Center","Line3":"Bismarck, ND 58501"},
{"State":"Ohio","Name":"Ohio Democratic Party","Line1":"340 East Fulton Street","Line2":"","Line3":"Columbus, OH 43215"},
{"State":"Oklahoma","Name":"Oklahoma Democrats","Line1":"3700 N Classen","Line2":"Suite 100","Line3":"Oklahoma City, OK 73118"},
{"State":"Oregon","Name":"Democratic Party of Oregon","Line1":"232 NE 9th Ave.","Line2":"","Line3":"Portland, OR 97232-2915"},
{"State":"Pennsylvania","Name":"Pennsylvania Democratic Party","Line1":"229 State Street","Line2":"","Line3":"Harrisburg, PA 17101"},
{"State":"Rhode Island","Name":"Rhode Island Democratic Party","Line1":"200 Metro Center Blvd.","Line2":"","Line3":"Warwick, RI  02886"},
{"State":"South Carolina","Name":"South Carolina Democratic Party","Line1":"915 Lady St.","Line2":"Suite 111","Line3":"Columbia, SC 29201"},
{"State":"South Dakota","Name":"South Dakota Democratic Party","Line1":"PO Box 1485","Line2":"","Line3":"Sioux Falls, SD 57101"},
{"State":"Tennessee","Name":"Tennessee Democratic Party","Line1":"1900 Church Street","Line2":"Suite 203","Line3":"Nashville, TN 37203"},
{"State":"Texas","Name":"Texas Democrats","Line1":"PO Box 116","Line2":"","Line3":"Austin, TX 78767"},
{"State":"Utah","Name":"Utah Democratic Party","Line1":"825 N. 300 W.","Line2":"Suite C400 ","Line3":"Salt Lake City, UT 84103"},
{"State":"Vermont","Name":"Vermont Democratic Party","Line1":"73 Main St.","Line2":"Suite 400","Line3":"Montpelier, VT 05602"},
{"State":"Virginia","Name":"Democratic Party of Virginia","Line1":"919 East Main Street","Line2":"Suite 2050","Line3":"Richmond, VA 23219"},
{"State":"Washington","Name":"Washington State Democrats","Line1":"PO Box 4027","Line2":"","Line3":"Seattle, WA 98194"},
{"State":"Washington D.C.","Name":"DC Democratic Party","Line1":"PO Box 50622","Line2":"","Line3":"Washington, DC 20091"},
{"State":"West Virginia","Name":"West Virginia Democratic Party","Line1":"PO Box 11926","Line2":"Suite 214","Line3":"Charleston, WV 25301"},
{"State":"Wisconsin","Name":"Democratic Party of Wisconsin","Line1":"15 N. Pinckney St","Line2":"Suite 200","Line3":"Madison, WI 53703"},
{"State":"Wyoming","Name":"Wyoming Democrats","Line1":"PO Box 1972","Line2":"","Line3":"Cheyenne, WY 82003"}]

module.exports = states